[package]
name = "penumbra-app"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
repository = {workspace = true}
homepage = {workspace = true}
license = {workspace = true}
publish = false

[features]
default = ["std"]
std = ["ark-ff/std", "ibc-types/std"]

[dependencies]
cnidarium = {workspace = true, default-features = true}
cnidarium-component = {workspace = true, default-features = true}
penumbra-proto = {workspace = true, features = ["cnidarium"], default-features = true}
penumbra-tct = {workspace = true, default-features = true}
penumbra-proof-params = {workspace = true, default-features = true}
penumbra-asset = {workspace = true, default-features = true}
penumbra-keys = {workspace = true, default-features = true}
penumbra-txhash = {workspace = true, default-features = true}
penumbra-num = {workspace = true, default-features = true}
penumbra-shielded-pool = {workspace = true, features = [
    "component",
], default-features = true}
penumbra-stake = {workspace = true, default-features = true}
penumbra-governance = {workspace = true, default-features = true}
penumbra-sct = {workspace = true, default-features = true}
penumbra-fee = {workspace = true, default-features = true}
penumbra-funding = {workspace = true, default-features = true}
penumbra-community-pool = {workspace = true, default-features = true}
penumbra-dex = {workspace = true, default-features = true}
penumbra-ibc = {workspace = true, features = ["component"], default-features = true}
penumbra-distributions = {workspace = true, default-features = true}
penumbra-compact-block = {workspace = true, default-features = true}
penumbra-transaction = {workspace = true, features = ["parallel"], default-features = true}
penumbra-genesis = {workspace = true}
decaf377 = {workspace = true, default-features = true}
decaf377-rdsa = {workspace = true}
jmt = {workspace = true}
tokio = {workspace = true, features = ["full", "tracing"]}
tokio-util = {workspace = true}
async-trait = {workspace = true}
tonic = {workspace = true}
futures = {workspace = true}
anyhow = {workspace = true}
tracing = {workspace = true}
ark-ff = {workspace = true, default-features = false}
blake2b_simd = {workspace = true}
bincode = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_with = {workspace = true}
metrics = {workspace = true}
sha2 = {workspace = true}
serde_json = {workspace = true}
serde_unit_struct = {workspace = true}
bech32 = {workspace = true}
im = {workspace = true}
regex = {workspace = true}
once_cell = {workspace = true}
bitvec = {workspace = true}
hex = {workspace = true}
base64 = {workspace = true}
tempfile = {workspace = true}
prost = {workspace = true}
rand_chacha = {workspace = true}
parking_lot = {workspace = true}
tendermint = {workspace = true}
tendermint-proto = {workspace = true}
tendermint-light-client-verifier = {workspace = true}
ibc-types = {workspace = true, default-features = false}
ibc-proto = {workspace = true, default-features = false, features = [
    "server",
]}
tower = {workspace = true, features = ["full"]}
tower-abci = "0.11"
tower-actor = "0.1.0"
tower-service = {workspace = true}
penumbra-tower-trace = { path = "../../util/tower-trace" }
ics23 = {workspace = true}

[dev-dependencies]
ed25519-consensus = {workspace = true}
penumbra-mock-consensus = {workspace = true}
penumbra-mock-client = {workspace = true}
rand_core = {workspace = true}
rand_chacha = {workspace = true}
tracing-subscriber = {workspace = true}

# Enable the feature flags to get proving keys when running tests.
[dev-dependencies.penumbra-proof-params]
workspace = true
features = [
    "bundled-proving-keys",
    "download-proving-keys",
]
