[package]
name = "penumbra-custody"
version = {workspace = true}
edition = {workspace = true}

[dependencies]
ark-ff = {workspace = true}
ark-serialize = {workspace = true}
blake2b_simd = {workspace = true}
chacha20poly1305 = {workspace = true}
decaf377 = {workspace = true}
decaf377-rdsa = {workspace = true}
decaf377-frost = { path = "../crypto/decaf377-frost" }
decaf377-ka = {workspace = true}
penumbra-keys = {workspace = true, default-features = true}
penumbra-txhash = {workspace = true, default-features = true}
penumbra-proto = {workspace = true, features = ["rpc"], default-features = true}
penumbra-transaction = {workspace = true, default-features = true}
tokio = {workspace = true, features = ["full"]}
anyhow = {workspace = true}
serde_json = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_with = {workspace = true, features = ["hex"]}
tracing = {workspace = true}
tonic = {workspace = true}
bytes = {workspace = true, features = ["serde"]}
prost = {workspace = true}
futures = {workspace = true}
hex = {workspace = true}
rand_core = {workspace = true}
ed25519-consensus = {workspace = true}
base64 = {workspace = true}

[dev-dependencies]
toml = {workspace = true}
