apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "relayer.fullname" . }}
  labels:
    {{- include "relayer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "relayer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "relayer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # The relayer exposes an API by default on localhost:5183; in our container entrypoint,
          # we set localhost:5100 on the `rly start` command. Doing so allows us to check
          # sockets on the container; if 5183 is open, it's still configuring; if 5100 is open,
          # then the service is actually running.
          ports:
            - containerPort: 5100
          startupProbe:
            tcpSocket:
              port: 5100
            # The container entrypoint will block for a while, building relayer config
            # from remote chain info. Let's give the relayer 10m to start up.
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
