[package]
name = "penumbra-wallet"
version = "0.55.0"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "The wallet software for the Penumbra Zone"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../proto" }
penumbra-tct = { path = "../crypto/tct" }
penumbra-crypto = { path = "../core/crypto" }
penumbra-num = { path = "../core/num" }
penumbra-asset = { path = "../core/asset" }
penumbra-chain = { path = "../core/component/chain" }
penumbra-transaction = { path = "../core/transaction" }
penumbra-app = { path = "../core/app" }
penumbra-stake = { path = "../core/component/stake" }
penumbra-fee = { path = "../core/component/fee" }
penumbra-view = { path = "../view" }
penumbra-custody = { path = "../custody" }

# External dependencies
bytes = "1"
bincode = "1.3.3"
tokio = { version = "1.21.1", features = ["full"]}
tower = { version = "0.4", features = ["full"]}
tonic = "0.8.1"
tracing = "0.1"
pin-project = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1.11", features = ["hex"] }
anyhow = "1"
hex = "0.4"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"

[dev-dependencies]
proptest = "1"
proptest-derive = "0.3"
once_cell = "1"

[features]
default = []
parallel = ["penumbra-transaction/parallel"]
