[package]
name = "penumbra-keys"
version = "0.55.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace deps
decaf377-ka = { path = "../../crypto/decaf377-ka/" }
decaf377-fmd = { path = "../../crypto/decaf377-fmd/" }
penumbra-proto = { path = "../../proto/" }
penumbra-tct = { path = "../../crypto/tct/", features = ["r1cs"] }
penumbra-asset = { path = "../../core/asset" }

# Git deps
decaf377 = {version = "0.4", features = ["r1cs"] }
decaf377-rdsa = { version = "0.6" }
poseidon377 = { version = "0.6", features = ["r1cs"] }
f4jumble = { git = "https://github.com/zcash/librustzcash", rev = "2425a0869098e3b0588ccd73c42716bcf418612c" }

# Crates.io deps
base64 = "0.20"
ark-ff = { version = "0.4", default_features = false }
ark-std = { version = "0.4", default_features = false }
ark-serialize = "0.4"
regex = "1.5"
sha2 = "0.10.1"
bech32 = "0.8.1"
aes = "0.8.1"
anyhow = "1"
thiserror = "1"
bytes = "1"
derivative = "2.2"
hex = "0.4"
hmac = "0.12.0"
# Not enabling js feature for getrandom, which is a transitive dep of rand_core,
# because the docs recommend against doing it in libraries: https://docs.rs/getrandom/latest/getrandom/#webassembly-support
# Downstream client projects can modify their Cargo.toml files to enable it.
# getrandom = { version = "0.2", features = ["js"] }
blake2b_simd = "0.5"
serde = { version = "1", features = ["derive"] }
once_cell = "1.8"
pbkdf2 = "0.12.0"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
chacha20poly1305 = "0.9.0"
ethnum = "1.3"
# temporary -- only used for division
ibig = "0.3"
# only needed because ark-ff doesn't display correctly
num-bigint = "0.4"
tracing = "0.1"
ark-groth16 = {version = "0.4", default-features = false}
ark-snark = "0.4"
ark-r1cs-std = {version = "0.4", default-features = false }
ark-relations = "0.4"

[dev-dependencies]
proptest = "1"
serde_json = "1"
frost377 = { version = "0.2", default-features=false }

[features]
default = []
parallel = ["penumbra-tct/parallel", "ark-ff/parallel", "poseidon377/parallel", "decaf377-rdsa/parallel", "ark-groth16/parallel", "ark-std/parallel", "ark-r1cs-std/parallel", "decaf377/parallel", "frost377/parallel"]
