[workspace]

# Also remember to add to .github/workflows/notes.yml
members = [
  "decaf377-fmd",
  "decaf377-ka",
  "proto",
  "crypto",
  "chain",
  "stake",
  "transaction",
  "wallet",
  "wallet-next",
  "pd",
  "pcli",
  "pcli-next",
  "tct",
  "tct-property-test",
  "ibc",
]

[patch.crates-io]
# The "ours" branch is based off of v0.3.0
ark-ff = { git = "https://github.com/penumbra-zone/algebra", branch = "ours" }
ark-serialize = { git = "https://github.com/penumbra-zone/algebra", branch = "ours" }
