[workspace]

exclude = [
    "tools/proto-compiler",
]

# Also remember to add to .github/workflows/notes.yml
members = [
  "decaf377-fmd",
  "decaf377-ka",
  "eddy",
  "proto",
  "chain",
  "component",
  "crypto",
  "custody",
  "measure",
  "storage",
  "storage2",
  "tct",
  "tct-property-test",
  "tct-visualize",
  "transaction",
  "wallet",
  "view",
  "pd",
  "pcli",
]
