[workspace]

exclude = [
    "tools/proto-compiler",
    "tools/parameter-setup",
]

# Also remember to add to scripts/rust-docs
members = [
  "decaf377-fmd",
  "decaf377-ka",
  "eddy",
  "proto",
  "chain",
  "component",
  "crypto",
  "custody",
  "measure",
  "storage",
  "tct",
  "tct-property-test",
  "tct-visualize",
  "transaction",
  "wallet",
  "view",
  "pd",
  "pcli",
  "proof-params",
]
