[workspace]

exclude = [
    "tools/proto-compiler",
    "tools/parameter-setup",
]

# Also remember to add to deployments/scripts/rust-docs
members = [
  "decaf377-fmd",
  "decaf377-ka",
  "eddy",
  "proto",
  "chain",
  "app",
  "crypto",
  "custody",
  "measure",
  "storage",
  "tct",
  "tct-property-test",
  "tct-visualize",
  "transaction",
  "wallet",
  "view",
  "pd",
  "pclientd",
  "pcli",
  "proof-params",
  "wasm",
]

# Optimize for small binaries in just the wasm crate.
[profile.release.package.penumbra-wasm]
opt-level = "s"
