[workspace]

# Also remember to add to .github/workflows/notes.yml
members = [
  "decaf377-fmd",
  "decaf377-ka",
  "proto",
  "chain",
  "component",
  "crypto",
  "custody",
  "measure",
  "storage",
  "tct",
  "tct-property-test",
  "transaction",
  "wallet",
  "view",
  "pd",
  "pcli",
]
