version: "3.7"
services:
  # The Penumbra daemon
  pd-node0:
    container_name: penumbra-node0
    build:
      context: .
    environment:
      - RUST_LOG=${RUST_LOG:-warn,pd=debug,penumbra=debug,jmt=info}
    volumes:
      - ~/.penumbra/testnet_data/node0/pd:/pd
    command: pd start --host 0.0.0.0 -r /pd/rocksdb
    restart: on-failure
    networks:
      localnet:
        ipv4_address: 192.167.10.10
    ports:
      - "26658:26658"
      - "8080:8080"

  # The Tendermint node
  tendermint-node0:
    image: "tendermint/tendermint:v0.35.4"
    container_name: tendermint-node0
    ports:
      - "26656:26656"
      - "26657:26657"
    volumes:
      - ~/.penumbra/testnet_data/node0/tendermint:/tendermint
    command: start --proxy-app=tcp://pd-node0:26658
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    depends_on:
      - pd-node0
    networks:
      localnet:
        ipv4_address: 192.167.10.11

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16
