version: "3.7"
services:
  # The Penumbra daemon
  pd:
    container_name: penumbra
    build:
      context: .
    environment:
      - RUST_LOG=${RUST_LOG:-warn,pd=info,penumbra=info}
    command: pd start --host 0.0.0.0 --database-uri
      postgres://postgres:postgres@db/penumbra
    restart: on-failure
    networks:
      localnet:
        ipv4_address: 192.167.10.6
    ports:
      - "26658:26658"
      - "26666:26666"

  # The Tendermint node
  tendermint:
    image: "tendermint/tendermint:latest"
    container_name: tendermint
    ports:
      - "26656-26657:26656-26657"
      - "6060:6060"
      - "27000:26660"
    volumes:
      - "tendermint_data:/tendermint"
    command: start --proxy-app=tcp://pd:26658
    depends_on:
      - pd
    networks:
      localnet:
        ipv4_address: 192.167.10.2

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16

volumes:
  tendermint_data: {}
