[package]
name = "penumbra-fee"
version = "0.64.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = ["cnidarium-component", "cnidarium", "penumbra-proto/cnidarium"]
default = ["std", "component"]
std = ["ark-ff/std"]
docsrs = []

[dependencies]
# Workspace dependencies
cnidarium = { path = "../../../cnidarium", optional = true }
cnidarium-component = { path = "../../../cnidarium-component", optional = true }
penumbra-proto = { path = "../../../proto", default-features = false }
penumbra-asset = { path = "../../../core/asset", default-features = false }
penumbra-num = { path = "../../../core/num", default-features = false }

# Penumbra dependencies
decaf377-rdsa = { version = "0.7" }
decaf377 = { version = "0.5" }

# Crates.io dependencies
ark-ff = { version = "0.4", default_features = false }
metrics = "0.19.0"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
anyhow = "1"
async-trait = "0.1.52"
tendermint = "0.34.0"
blake2b_simd = "0.5"
bytes = "1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
