[package]
name = "penumbra-fee"
version = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "penumbra-proto/cnidarium",
    "tonic",
]
default = ["std", "component"]
std = ["ark-ff/std"]
docsrs = []

[dependencies]
cnidarium = {workspace = true, optional = true, default-features = true}
cnidarium-component = {workspace = true, optional = true, default-features = true}
penumbra-proto = {workspace = true, default-features = false}
penumbra-asset = {workspace = true, default-features = false}
penumbra-num = {workspace = true, default-features = false}
decaf377-rdsa = {workspace = true}
decaf377 = {workspace = true, default-features = true}
ark-ff = {workspace = true, default-features = false}
metrics = {workspace = true}
serde = {workspace = true, features = ["derive"]}
tracing = {workspace = true}
anyhow = {workspace = true}
async-trait = {workspace = true}
tendermint = {workspace = true}
blake2b_simd = {workspace = true}
bytes = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
rand = {workspace = true}
tonic = {workspace = true, optional = true}
