[package]
name = "penumbra-governance"
version = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-sct/component",
    "penumbra-stake/component",
    "tokio",
    "tonic",
]
# proving-keys = ["penumbra-proof-params/proving-keys"]
default = ["std", "component"]
std = ["ark-ff/std", "ibc-types/std"]
parallel = [
    "penumbra-tct/parallel",
    "ark-ff/parallel",
    "decaf377-rdsa/parallel",
    "ark-groth16/parallel",
    "ark-r1cs-std/parallel",
    "decaf377/parallel",
]
docsrs = []

[dependencies]
cnidarium = {workspace = true, optional = true, default-features = true}
cnidarium-component = {workspace = true, optional = true, default-features = true}
penumbra-proto = {workspace = true, default-features = false}
penumbra-tct = {workspace = true, default-features = true}
penumbra-proof-params = {workspace = true, default-features = false}
penumbra-sct = {workspace = true, default-features = false}
penumbra-shielded-pool = {workspace = true, default-features = false}
penumbra-stake = {workspace = true, default-features = false}
penumbra-community-pool = {workspace = true, default-features = false}
penumbra-fee = {workspace = true, default-features = false}
penumbra-funding = {workspace = true, default-features = false}
penumbra-ibc = {workspace = true, default-features = false}
penumbra-distributions = {workspace = true, default-features = false}
penumbra-asset = {workspace = true, default-features = false}
penumbra-keys = {workspace = true, default-features = false}
penumbra-txhash = {workspace = true, default-features = false}
penumbra-num = {workspace = true, default-features = false}
decaf377-rdsa = {workspace = true}
decaf377 = {workspace = true, features = ["r1cs"], default-features = true}
base64 = {workspace = true}
ark-r1cs-std = {workspace = true, default-features = false}
ark-relations = {workspace = true}
ark-ff = {workspace = true, default-features = false}
ark-serialize = {workspace = true}
ark-groth16 = {workspace = true, default-features = false}
ark-snark = {workspace = true}
async-stream = {workspace = true}
metrics = {workspace = true}
serde = {workspace = true, features = ["derive"]}
tracing = {workspace = true}
anyhow = {workspace = true}
async-trait = {workspace = true}
tendermint = {workspace = true}
blake2b_simd = {workspace = true}
bytes = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
rand = {workspace = true}
im = {workspace = true}
regex = {workspace = true}
futures = {workspace = true}
pbjson-types = {workspace = true}
once_cell = {workspace = true}
rand_chacha = {workspace = true}
ibc-types = {workspace = true, default-features = false}
tokio = {workspace = true, features = ["full", "tracing"], optional = true}
tonic = {workspace = true, optional = true}

[dev-dependencies]
proptest = {workspace = true}
proptest-derive = {workspace = true}
