[package]
name = "penumbra-tct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2"
once_cell = "1"
blake2b_simd = "1"
hex = "0.4"
hash_hasher = "2"
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
ark-ff = { git = "https://github.com/penumbra-zone/algebra", branch = "ours" }
ark-serialize = { git = "https://github.com/penumbra-zone/algebra", branch = "ours" }
poseidon377 = { git = "https://github.com/penumbra-zone/poseidon377" }
decaf377 = { git = "https://github.com/penumbra-zone/decaf377" }

[dev-dependencies]
static_assertions = "1"
proptest = "1"