[package]
name = "penumbra-tct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penumbra-proto = { path = "../proto/" }

derivative = "2"
once_cell = "1"
blake2b_simd = "1"
hex = "0.4"
hash_hasher = "2"
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
parking_lot = "0.12"
ark-ff = "0.3"
ark-serialize = "0.3"
poseidon377 = { git = "https://github.com/penumbra-zone/poseidon377" }
decaf377 = { git = "https://github.com/penumbra-zone/decaf377" }
proptest = { version = "1", optional = true }
proptest-derive = { version = "0.3", optional = true }
rand = { version = "0.8", optional = true }

[features]
internal = []
arbitrary = ["proptest", "proptest-derive", "rand"]

[dev-dependencies]
static_assertions = "1"
proptest = "1"
proptest-derive = "0.3"
penumbra-tct = { path = ".", features = ["arbitrary"] }
serde_json = "1"
bincode = "1"