[package]
name = "psumcoordd"
version = "0.60.0"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "Coordination node for summoning ceremony"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false
# Pin a MSRV. Anything more recent than this value is OK.
# If a lower version is used for build, the build will fail.
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bytes = "1"
camino = "1"
clap = { version = "3", features = ["derive", "env"] }
http-body = "0.4.5"
penumbra-keys = { path = "../../core/keys/" }
penumbra-view = { path = "../../view/" }
penumbra-proto = { path = "../../proto/" } 
tokio = { version = "1.22", features = ["full"] }
tonic = "0.9"
tower = "0.4"
url = "2"

[build-dependencies]
vergen = "5"

