[package]
name = "penumbra-community-pool"
version = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-shielded-pool/component",
]
default = ["component"]
docsrs = []

[dependencies]
cnidarium = {workspace = true, optional = true, default-features = true}
cnidarium-component = {workspace = true, optional = true, default-features = true}
penumbra-proto = {workspace = true, default-features = false}
penumbra-shielded-pool = {workspace = true, default-features = false}
penumbra-sct = {workspace = true, default-features = false}
penumbra-asset = {workspace = true, default-features = false}
penumbra-num = {workspace = true, default-features = false}
penumbra-keys = {workspace = true, default-features = false}
penumbra-txhash = {workspace = true, default-features = false}
ark-ff = {workspace = true, default-features = false}
async-trait = {workspace = true}
hex = {workspace = true}
anyhow = {workspace = true}
tracing = {workspace = true}
prost = {workspace = true}
serde = {workspace = true, features = ["derive"]}
metrics = {workspace = true}
pbjson-types = {workspace = true}
tendermint = {workspace = true}
tendermint-light-client-verifier = {workspace = true}
sha2 = {workspace = true}
once_cell = {workspace = true}
base64 = {workspace = true}
blake2b_simd = {workspace = true}
futures = {workspace = true}

[dev-dependencies]
tokio = {workspace = true, features = ["full"]}
