[package]
name = "summonerd"
version = "0.62.0"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "Coordination node for summoning ceremony"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false
# Pin a MSRV. Anything more recent than this value is OK.
# If a lower version is used for build, the build will fail.
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
atty = "0.2"
bytes = "1"
camino = "1"
clap = { version = "3", features = ["derive", "env"] }
console-subscriber = "0.1.8"
futures = "0.3.28"
http-body = "0.4.5"
metrics-tracing-context = "0.11.0"
penumbra-asset = { path = "../../crates/core/asset/" }
penumbra-keys = { path = "../../crates/core/keys/" }
penumbra-num = { path = "../../crates/core/num/" }
penumbra-proof-setup = { path = "../../crates/crypto/proof-setup/" }
penumbra-proto = { path = "../../crates/proto/" } 
penumbra-view = { path = "../../crates/view/" }
rand = "0.8"
tokio = { version = "1.22", features = ["full"] }
tokio-stream = "0.1"
tonic = "0.10"
tonic-web = "0.10"
tower = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2"
r2d2 = "0.8"
# Depending on our fork of r2d2-sqlite, which updates the rusqlite dependency to 0.29
r2d2_sqlite = { version = "0.22", git = "https://github.com/penumbra-zone/r2d2-sqlite.git", features = [
    "bundled",
] }

[build-dependencies]
vergen = "5"

