[package]
name = "summonerd"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
description = "Coordination node for summoning ceremony"
repository = {workspace = true}
homepage = {workspace = true}
license = {workspace = true}
publish = false
rust-version = "1.65"

[dependencies]
anyhow = {workspace = true}
ark-groth16 = {workspace = true}
ark-serialize = {workspace = true}
askama = "0.11"
async-trait = {workspace = true}
axum = {workspace = true}
bytes = {workspace = true}
camino = {workspace = true}
chrono = {workspace = true}
clap = {workspace = true, features = ["derive", "env", "color"]}
decaf377 = {workspace = true}
futures = {workspace = true}
hex = {workspace = true}
http-body = {workspace = true}
metrics-tracing-context = {workspace = true}
penumbra-asset = {workspace = true, default-features = true}
penumbra-keys = {workspace = true, default-features = true}
penumbra-num = {workspace = true, default-features = true}
penumbra-proof-params = {workspace = true, default-features = true}
penumbra-proof-setup = {workspace = true, features = ["parallel"]}
penumbra-proto = {workspace = true, default-features = true}
penumbra-view = {workspace = true}
r2d2 = {workspace = true}
r2d2_sqlite = {workspace = true, features = ["bundled"]}
rand = {workspace = true}
rand_core = {workspace = true}
tokio = {workspace = true, features = ["full"]}
tokio-stream = {workspace = true}
tonic = {workspace = true}
tower = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
url = {workspace = true}
