[package]
# TODO: merge with tct crate under a `component` feature flag?
name = "penumbra-sct"
version = "0.62.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = [
    "penumbra-component",
    "penumbra-storage",
    "penumbra-proto/penumbra-storage",
    "penumbra-chain/component",
    "tonic",
]
default = ["std", "component"]
std = ["ark-ff/std"]
docsrs = []

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../../../proto", default-features = false }
penumbra-storage = { path = "../../../storage", optional = true }
penumbra-tct = { path = "../../../crypto/tct" }
penumbra-chain = { path = "../chain", default-features = false }
penumbra-keys = { path = "../../../core/keys", default-features = false }
penumbra-component = { path = "../component", optional = true }

# Penumbra dependencies
decaf377 = { version = "0.5", features = ["r1cs"] }
poseidon377 = { version = "0.6", features = ["r1cs"] }
decaf377-rdsa = { version = "0.7" }

# Crates.io dependencies
ark-r1cs-std = { version = "0.4", default-features = false }
ark-relations = "0.4"
ark-ff = { version = "0.4", default_features = false }
ark-serialize = "0.4"
metrics = "0.19.0"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
anyhow = "1"
async-trait = "0.1.52"
tendermint = "0.34.0"
blake2b_simd = "0.5"
bytes = "1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
bincode = "1.3.3"
once_cell = "1.8"
hex = "0.4"

# Component dependencies
tonic = { version = "0.10", optional = true }
