[package]
name = "penumbra-sct"
version = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium",
    "cnidarium-component",
    "penumbra-proto/cnidarium",
    "penumbra-proto/rpc",
    "tonic",
]
default = ["std", "component"]
std = ["ark-ff/std"]
docsrs = []

[dependencies]
cnidarium = {workspace = true, optional = true, default-features = true}
cnidarium-component = {workspace = true, optional = true, default-features = true}
penumbra-proto = {workspace = true, default-features = false}
penumbra-tct = {workspace = true, default-features = true}
penumbra-keys = {workspace = true, default-features = false}
decaf377 = {workspace = true, features = ["r1cs"], default-features = true}
poseidon377 = {workspace = true, features = ["r1cs"]}
decaf377-rdsa = {workspace = true}
ark-r1cs-std = {workspace = true, default-features = false}
ark-relations = {workspace = true}
ark-ff = {workspace = true, default-features = false}
ark-serialize = {workspace = true}
metrics = {workspace = true}
serde = {workspace = true, features = ["derive"]}
tracing = {workspace = true}
anyhow = {workspace = true}
async-trait = {workspace = true}
tendermint = {workspace = true}
blake2b_simd = {workspace = true}
bytes = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
rand = {workspace = true}
bincode = {workspace = true}
once_cell = {workspace = true}
hex = {workspace = true}
im = {workspace = true}
tonic = {workspace = true, optional = true}
