[book]
authors = ["Penumbra Team"]
language = "en"
multilingual = false
src = "src"
title = "The Penumbra Protocol"

[preprocessor.katex]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
curly-quotes = true
fold = { enable = true, level = 1 }
git-repository-url = "https://github.com/penumbra-zone/penumbra"
additional-js =["theme/js/mermaid.min.js", "theme/js/mermaid-init.js"]

# Documenting config for `mdbook-linkcheck`. We don't have this
# enabled in CI yet, but it's sure handy for fixing up links.
# [output.linkcheck]
# follow-web-links = false
# warning-policy = "ignore"
