[package]
name = "penumbra-funding"
version = "0.65.0-alpha.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-chain/component",
    "penumbra-community-pool/component",
    "penumbra-distributions/component",
    "penumbra-sct/component",
    "penumbra-shielded-pool/component",
    "penumbra-stake/component",
    "futures"
]
default = ["component"]
docsrs = []

[dependencies]

# Workspace dependencies
cnidarium-component = { path = "../../../cnidarium-component", optional = true }
penumbra-asset = { path = "../../asset" }
#penumbra-chain = { path = "../chain", default-features = false }
penumbra-community-pool = { path = "../community-pool", default-features = false }
penumbra-distributions = { path = "../distributions", default-features = false }
penumbra-proto = { path = "../../../proto", default-features = false }
penumbra-stake = { path = "../stake", default-features = false }
penumbra-sct = { path = "../sct", default-features = false }
penumbra-shielded-pool = { path = "../shielded-pool", default-features = false }
cnidarium = { path = "../../../cnidarium", optional = true }

# Crates.io deps
async-trait = "0.1.52"
anyhow = "1"
tracing = "0.1"
tendermint = "0.34.0"
futures = { version = "0.3", optional = true }

serde = { version = "1", features = ["derive"] }

[dev-dependencies]
