{{ $count := (.Values.numFullNodes | int) }}
{{ range $i,$e := until $count }}
---
kind: Service
apiVersion: v1
metadata:
  name: "p2p-fn-{{$i}}"
  labels:
    app: "p2p-fn-{{$i}}"
spec:
  type: LoadBalancer
  selector:
    app: "penumbra-fn-{{$i}}"
  ports:
    - protocol: TCP
      port: 26656
      targetPort: p2p
      name: tm-p2p
{{ if eq $i 0 }}
    - protocol: TCP
      port: 26657
      targetPort: rpc
      name: tm-rpc
    - protocol: TCP
      port: 8080
      targetPort: grpc
      name: pd-grpc      
{{ end }}
{{ end }}
