apiVersion: v1
kind: ConfigMap
metadata:
  name: tm-config-fn
data:
  config.toml: |
    proxy_app = "tcp://localhost:26658"

    [rpc]
    laddr = "tcp://0.0.0.0:26657"

    [p2p]
    max_num_inbound-peers = 50
    max_num_outbound-peers = 50

    persistent_peers = "{{ $.Files.Get "pdcli/persistent_peers.txt" | trim }}"
    private_peer_ids = "{{ $.Files.Get "pdcli/private_peers.txt" | trim }}"

    [tx_index]
    indexer = "null"

    [instrumentation]
    prometheus = true
