apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ include "penumbra.fullname" . }}-backend-config
  labels:
    {{- include "penumbra.labels" $ | nindent 4 }}
spec:
  timeoutSec: 600
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 5
    port: 1251
    type: HTTP
    requestPath: /
