apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "penumbra.fullname" . }}-genesis-config
  labels:
    {{- include "penumbra.labels" . | nindent 4 }}
binaryData:
{{ $path := "pdcli/genesis.json.gz" }}
{{- "genesis.json.gz" | indent 2 }}{{ print ": "}}{{ $.Files.Get $path | b64enc -}}
