{{- if .Values.ingress.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "penumbra.fullname" . }}-https
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.hosts.grpc }}`)
    services:
    - name: {{ include "penumbra.fullname" . }}-p2p-fn-0
      port: 8080
      scheme: h2c
  - kind: Rule
    match: Host(`{{ .Values.ingress.hosts.rpc }}`)
    services:
    - name: {{ include "penumbra.fullname" . }}-p2p-fn-0
      port: 26657
  - kind: Rule
    match: Host(`{{ .Values.ingress.hosts.grafana }}`)
    services:
    - name: {{ include "penumbra.fullname" . }}-metrics-grafana
      port: 80
  tls:
    domains:
    - main: {{ .Values.ingress.hosts.grpc }}
      sans:
        - {{ .Values.ingress.hosts.rpc }}
        - {{ .Values.ingress.hosts.grafana }}
    secretName: {{ include "penumbra.fullname" . }}-wildcard
{{- end }}
