[package]
name = "penumbra-transaction"
version = "0.55.0"
edition = "2021"

[dependencies]
# Workspace deps
penumbra-proto = { path = "../../proto/" }
# TODO: just use existing re-exports from penumbra-crypto instead of direct decaf-* deps?
decaf377-ka = { path = "../../crypto/decaf377-ka/" }
decaf377-fmd = { path = "../../crypto/decaf377-fmd/" }
penumbra-tct = { path = "../../crypto/tct" }
penumbra-proof-params = { path = "../../crypto/proof-params/", features = ["proving-keys"] }
penumbra-crypto = { path = "../crypto/" }
penumbra-chain = { path = "../component/chain/", default-features = false }
penumbra-governance = { path = "../component/governance/", default-features = false }
penumbra-shielded-pool = { path = "../component/shielded-pool/", default-features = false }
penumbra-stake = { path = "../component/stake", default-features = false }
penumbra-ibc = { path = "../component/ibc/", default-features = false }
penumbra-dao = { path = "../component/dao/", default-features = false }
penumbra-dex = { path = "../component/dex/", default-features = false }
penumbra-fee = { path = "../component/fee/", default-features = false }

# Git deps
ibc-types2 = { git = "https://github.com/penumbra-zone/ibc-types", branch = "main", default-features = false }

# Crates.io deps
ibc-proto = { version = "0.31.0", default-features = false }
decaf377 = "0.4"
decaf377-rdsa = { version = "0.6" }
poseidon377 = { version = "0.4", features = ["r1cs"] }
base64 = "0.21"
ark-ff = { version = "0.4", default_features = false }
ark-serialize = "0.4"
regex = "1.5"
sha2 = "0.9"
bech32 = "0.8.1"
aes = "0.7"
anyhow = "1"
thiserror = "1"
bytes = "1"
derivative = "2.2"
hex = "0.4"
blake2b_simd = "0.5"
serde = { version = "1", features = ["derive"] }
once_cell = "1.8"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
chacha20poly1305 = "0.9.0"
pbjson-types = "0.5"
# only needed because ark-ff doesn't display correctly
num-bigint = "0.4"
serde_json = "1"
tracing = "0.1"
tokio = { version = "1.21.1", features = ["full"], optional = true }
clap = { version = "3", features = ["derive"], optional = true }

[dev-dependencies]
proptest = "1"
proptest-derive = "0.3"
serde_json = "1"

[features]
default = ["std", "parallel"]
std = ["ark-ff/std"]
parallel = ["tokio", "penumbra-crypto/parallel"]
download-proving-keys = ["penumbra-proof-params/download-proving-keys"]
