[package]
name = "penumbra-ibc"
version = "0.58.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = ["penumbra-component", "penumbra-storage", "penumbra-proto/penumbra-storage", "penumbra-chain/component", "penumbra-shielded-pool/component"]
default = ["component", "std"]
std = ["ibc-types/std"]
docsrs = []

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../../../proto", default-features = false }
penumbra-storage = { path = "../../../storage", optional = true }
penumbra-component = { path = "../component", optional = true }
penumbra-chain = { path = "../chain", default-features = false }
penumbra-shielded-pool = { path = "../shielded-pool", default-features = false }
penumbra-asset = { path = "../../../core/asset", default-features = false  } 
penumbra-num = { path = "../../../core/num", default-features = false  } 
penumbra-keys = { path = "../../../core/keys", default-features = false  } 

# Penumbra dependencies
ibc-types = { git = "https://github.com/penumbra-zone/ibc-types", rev = "99d1484398f13aa35578948d34537bb8bb9848d9", default-features = false }
ibc-proto = { version = "0.31.0", default-features = false }

# Crates.io deps
ics23 = "0.10.1"
num-traits = { version = "0.2.15", default-features = false }
ark-ff = { version = "0.4", default_features = false }
async-trait = "0.1.52"
hex = "0.4"
anyhow = "1"
tracing = "0.1"
prost = "0.11"
serde = { version = "1", features = ["derive"] }
metrics = "0.19.0"
pbjson-types = "0.5.1"
tendermint = "0.32.0"
tendermint-light-client-verifier = "0.32.0"
sha2 = "0.10.6"
once_cell = "1.17.1"
base64 = "0.20"
blake2b_simd = "0.5"

[dev-dependencies]
tokio = {version = "1.3", features = ["full"]}
