[package]
name = "penumbra-sdk-txhash"
version = {workspace = true}
edition = {workspace = true}

[dependencies]
anyhow = {workspace = true}
blake2b_simd = {workspace = true}
hex = {workspace = true}
penumbra-sdk-proto = {workspace = true, default-features = false}
penumbra-sdk-tct = {workspace = true, default-features = true}
serde = {workspace = true}
getrandom = {workspace = true}
