[book]
authors = ["Penumbra Team"]
language = "en"
multilingual = false
src = "src"
title = "The Penumbra Guide"

[preprocessor.katex]
renderers = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
curly-quotes = true
fold = { enable = true, level = 2 }
git-repository-url = "https://github.com/penumbra-zone/penumbra"
additional-js =["theme/js/mermaid.min.js", "theme/js/mermaid-init.js"]

[output.linkcheck]
# Consider setting `follow-web-links=true` ad-hoc, to validate external URLs.
follow-web-links = false
warning-policy = "error"

# The buf.build website doesn't support HTTP HEAD calls, returning 405.
# Only relevant when `follow-web-links=true`.
exclude = ['buf\.build']

[output.html.redirect]
# Renames in GH4215.
"pd.html" = "node/pd.html"
"pd/chain-upgrade.html" = "node/pd/chain-upgrade.html"
"pd/debugging.html" = "node/pd/debugging.html"
"pd/install.html" = "node/pd/install.html"
"pd/join-testnet.html" = "node/pd/join-testnet.html"
"pd/requirements.html" = "node/pd/requirements.html"
"pd/validator.html" = "node/pd/validator.html"
"pclientd.html" = "node/pclientd.html"
"pclientd/build_transaction.html" = "node/pclientd/build_transaction.html"
"pclientd/configure.html" = "node/pclientd/configure.html"
"pclientd/rpc.html" = "node/pclientd/rpc.html"
