[package]
name = "cnidarium-component"
version = {workspace = true}
edition = {workspace = true}

[dependencies]
cnidarium = {workspace = true, default-features = false}
async-trait = {workspace = true}
anyhow = {workspace = true}
tendermint = {workspace = true}
hex = {workspace = true}
