[package]
name = "penumbra-proto-compiler"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
prost = "0.11"
prost-types = "0.11"
prost-build = "0.11"
prost-wkt-types = "0.3.4"
tonic-build = "0.8.0"

ibc-proto = "0.22.0"
ics23 = "0.8.1"
prost-wkt-build = "0.3"
