[package]
name = "penumbra-proto-compiler"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
prost = "0.11"
prost-types = "0.11"
prost-build = "0.11"
tonic-build = "0.8.0"

ibc-proto = { git = "https://github.com/cosmos/ibc-proto-rs", tag = "v0.22.0" }
ics23 = { git = "https://github.com/cosmos/ics23" }
