[package]
name = "pmonitor"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {workspace = true}
camino = {workspace = true}
clap = {workspace = true, features = ["derive", "env"]}
colored = "2.1.0"
directories = {workspace = true}
futures = {workspace = true}
indicatif = {workspace = true}
pcli = {path = "../pcli", default-features = true}
penumbra-sdk-app = {workspace = true}
penumbra-sdk-asset = {workspace = true, default-features = false}
penumbra-sdk-compact-block = {workspace = true, default-features = false}
penumbra-sdk-keys = {workspace = true, default-features = false}
penumbra-sdk-num = {workspace = true, default-features = false}
penumbra-sdk-proto = {workspace = true}
penumbra-sdk-shielded-pool = {workspace = true, default-features = false}
penumbra-sdk-stake = {workspace = true, default-features = false}
penumbra-sdk-tct = {workspace = true, default-features = false}
penumbra-sdk-view = {workspace = true}
regex = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
tokio = {workspace = true, features = ["full"]}
toml = {workspace = true}
tonic = {workspace = true, features = ["tls-webpki-roots", "tls"]}
tracing = {workspace = true}
tracing-subscriber = { workspace = true, features = ["env-filter", "ansi"] }
url = {workspace = true, features = ["serde"]}
uuid = { version = "1.3", features = ["v4", "serde"] }

[dev-dependencies]
assert_cmd = {workspace = true}
once_cell = {workspace = true}
tempfile = {workspace = true}
