[package]
name = "pmonitor"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {workspace = true}
clap = {workspace = true, features = ["derive", "env"]}
tracing = {workspace = true}
tokio = {workspace = true, features = ["full"]}
penumbra-compact-block = {workspace = true, default-features = false}
penumbra-keys = {workspace = true, default-features = false}
penumbra-shielded-pool = {workspace = true, default-features = false}
penumbra-tct = {workspace = true, default-features = false}
directories = {workspace = true}
camino = {workspace = true}
url = {workspace = true, features = ["serde"]}
toml = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
futures = {workspace = true}
