{{ $count := (.Values.numFullNodes | int) }}
{{ range $i,$e := until $count }}
{{ $tm_config := printf "config-%s-fn-%d" (include "tendermint.name" $) $i }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $tm_config }}
  labels:
    {{- include "penumbra.labels" $ | nindent 4 }}
data:
  config.toml: |
    proxy_app = "tcp://localhost:26658"

    [rpc]
    laddr = "tcp://0.0.0.0:26657"

    [p2p]
    max_num_inbound-peers = 50
    max_num_outbound-peers = 50

    persistent_peers = "{{ $.Files.Get (printf "pdcli/persistent_peers_fn_%d.txt" $i) | trim }}"
    external_address = "{{ $.Files.Get (printf "pdcli/external_address_fn_%d.txt" $i) | trim }}"

    [tx_index]
    indexer = "null"

    [instrumentation]
    prometheus = true
{{ end }}
