apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "penumbra.fullname" . }}-genesis-config
  labels:
    {{- include "penumbra.labels" . | nindent 4 }}
binaryData:
{{ $path := "pdcli/.penumbra/testnet_data/node0/tendermint/config/genesis.json" }}
{{- "genesis.json" | indent 2 }}{{ print ": "}}{{ $.Files.Get $path | b64enc -}}
