[package]
name = "penumbra-dex"
version = "0.52.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = ["penumbra-component", "penumbra-storage", "penumbra-proto/penumbra-storage", "penumbra-chain/component", "penumbra-shielded-pool/component", "tokio"]
default = ["component", "proving-keys"]
docsrs = []
proving-keys = ["penumbra-proof-params/proving-keys"]

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../../proto", default-features = false }
penumbra-storage = { path = "../../storage", optional = true }
penumbra-component = { path = "../component", optional = true }
penumbra-chain = { path = "../../chain", default-features = false }
penumbra-crypto = { path = "../../crypto", default-features = false }
penumbra-shielded-pool = { path = "../shielded-pool", default-features = false }
penumbra-sct = { path = "../sct", default-features = false }
penumbra-tct = { path = "../../tct", default-features = false }
penumbra-proof-params = { path = "../../proof-params" }

# Penumbra dependencies
poseidon377 = { version = "0.4", features = ["r1cs"] }
decaf377 = {version = "0.4", features = ["r1cs"] }

# Crates.io deps
ark-r1cs-std = {version = "0.4", default-features = false }
ark-relations = "0.4"
ark-ff = { version = "0.4", default_features = false }
ark-serialize = "0.4"
ark-groth16 = {version = "0.4", default-features = false}
ark-snark = "0.4"
async-trait = "0.1.52"
tokio = {version = "1.3", features = ["full"], optional = true} 
hex = "0.4"
anyhow = "1"
tracing = "0.1"
prost = "0.11"
serde = { version = "1", features = ["derive"] }
metrics = "0.19.0"
pbjson-types = "0.5.1"
tendermint = "0.29.0"
tendermint-light-client-verifier = "0.29.0"
sha2 = "0.10.6"
once_cell = "1.17.1"
base64 = "0.20"
blake2b_simd = "0.5"
futures = "0.3.28"
im = "15.1.0"
parking_lot = "0.12.1"
rand_core = "0.6.4"
regex = "1.8.1"

[dev-dependencies]
proptest = "1"
rand = "0.8.5"
serde_json = "1.0.96"
tracing-subscriber = "0.3.17"
