apiVersion: v1
kind: ConfigMap
metadata:
  name: tm-config
data:
  config.toml: |
    [p2p]
    max-num-inbound-peers = 50
    max-num-outbound-peers = 50

    [tx_index]
    indexer = "null"

    [instrumentation]
    prometheus = true
