apiVersion: v1
kind: ConfigMap
metadata:
  name: tm-config
data:
  config.toml: |
    [p2p]
    seeds = ""

    persistent-peers = "{{ $.Files.Get "persistent_peers.txt" | trim }}"

    max-num-inbound_peers = 50
    max-num-outbound_peers = 50

    [tx_index]
    indexer = "null"

    [instrumentation]
    prometheus = true
