{{ $count := (.Values.numValidators | int) }}
{{ range $i,$e := until $count }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "tm-config-val-{{$i}}"
data:
  config.toml: |
    proxy-app = "tcp://localhost:26658"

    [p2p]
    max-num-inbound-peers = 50
    max-num-outbound-peers = 50

    persistent-peers = "{{ $.Files.Get (printf "pdcli/persistent_peers_%d.txt" $i) | trim }}"
    private-peer-ids = "{{ $.Files.Get "pdcli/private_peers.txt" | trim }}"

    [tx_index]
    indexer = "null"

    [instrumentation]
    prometheus = true
{{ end }}