[package]
name = "penumbra-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penumbra-proto = { path = "../proto" }
penumbra-crypto = { path = "../crypto" }
penumbra-tct = { path = "../tct" }

tokio = { version = "1.21.1", features = ["full", "tracing"]}
sha2 = "0.9"
tempfile = "3.3.0"
jmt = { git = "https://github.com/penumbra-zone/jellyfish-merkle.git", branch = "main" }
ibc-proto = { git = "https://github.com/penumbra-zone/ibc-rs.git", branch = "with-tendermintrs-24" }
ibc = { git = "https://github.com/penumbra-zone/ibc-rs.git", branch = "with-tendermintrs-24" }
anyhow = "1"
once_cell = "1.8"
bincode = "1.3"
tendermint = "=0.24.0-pre.1"
async-trait = "0.1.52"
tracing = "0.1"
rocksdb = "0.18.0"
futures = "0.3"
tonic = "0.6.1"
hex = "0.4"
metrics = "0.19.0"
ics23 = "=0.7.0"
