apiVersion: v1
kind: ConfigMap
metadata:
  name: tm-config
data:
  config.toml: |
    [p2p]
    seeds = "0f04c4610b7511a64b8644944b907416db568590@104.155.134.255:26656"
    persistent_peers = "867a241fe58d03ca711625478706eee2dac17dba@testnet.penumbra.zone:26656"
    max_num_inbound_peers = 50
    max_num_outbound_peers = 50

    [tx_index]
    indexer = "null"

    [instrumentation]
    prometheus = true
