[package]
name = "penumbra-distributions"
version = "0.62.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = ["penumbra-component", "penumbra-storage", "penumbra-proto/penumbra-storage", "penumbra-chain/component", "penumbra-shielded-pool/component"]
default = ["component"]
docsrs = []

[dependencies]

# Workspace dependencies
penumbra-proto = { path = "../../../proto", default-features = false }
penumbra-storage = { path = "../../../storage", optional = true }
penumbra-component = { path = "../component", optional = true }
penumbra-chain = { path = "../chain", default-features = false }
penumbra-shielded-pool = { path = "../shielded-pool", default-features = false }

# Crates.io deps
async-trait = "0.1.52"
anyhow = "1"
tracing = "0.1"
tendermint = "0.34.0"

[dev-dependencies]
