[package]
name = "penumbra-distributions"
version = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-sct/component",
]
default = ["component"]
docsrs = []

[dependencies]
cnidarium = {workspace = true, optional = true, default-features = true}
cnidarium-component = {workspace = true, optional = true, default-features = true}
penumbra-asset = {workspace = true, default-features = false}
penumbra-num = {workspace = true, default-features = false}
penumbra-proto = {workspace = true, default-features = false}
penumbra-sct = {workspace = true, default-features = false}
async-trait = {workspace = true}
anyhow = {workspace = true}
tracing = {workspace = true}
tendermint = {workspace = true}
serde = {workspace = true, features = ["derive"]}

[dev-dependencies]
