[package]
name = "penumbra-distributions"
version = "0.64.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-chain/component",
    "penumbra-shielded-pool/component",
]
default = ["component"]
docsrs = []

[dependencies]

# Workspace dependencies
penumbra-asset = { path = "../../asset" }
cnidarium-component = { path = "../../../cnidarium-component", optional = true }
penumbra-chain = { path = "../chain", default-features = false }
penumbra-num = { path = "../../../core/num", default-features = false }
penumbra-proto = { path = "../../../proto", default-features = false }
penumbra-shielded-pool = { path = "../shielded-pool", default-features = false }
cnidarium = { path = "../../../cnidarium", optional = true }

# Crates.io deps
async-trait = "0.1.52"
anyhow = "1"
tracing = "0.1"
tendermint = "0.34.0"

serde = { version = "1", features = ["derive"] }

[dev-dependencies]
