scrape_configs:
  - job_name: 'CometBFT Node'
    scrape_interval: 10s
    scheme: http
    metrics_path: metrics
    static_configs:
      # Using localhost for scrape targets requires `--network=host` on container run args.
      - targets: ['127.0.0.1:26660']
  - job_name: 'Penumbra Daemon'
    scrape_interval: 10s
    scheme: http
    metrics_path: metrics
    static_configs:
      - targets: ['127.0.0.1:9000']
