scrape_configs:
  - job_name: 'Tendermint Node'
    scrape_interval: 10s
    scheme: http
    metrics_path: metrics
    static_configs:
      # TODO: The hostname isn't working here, but the IP is hardcoded in docker-compose.yml so this works for now
      - targets: ['192.167.10.11:26660']
  # NOTE: `pd` doesn't actually expose metrics yet, so this doesn't actually do
  # anything interesting...
  - job_name: 'Penumbra Daemon'
    scrape_interval: 10s
    scheme: http
    metrics_path: metrics
    static_configs:
      - targets: ['192.167.10.10:9000']
