[package]
name = "penumbra-bench"
version = {workspace = true}
edition = {workspace = true}

[build-dependencies]
regex = { version = "1", optional = true }
reqwest = { version = "0.11.14", optional = true, features = [
    "blocking",
    "json",
] }
serde_json = { version = "1", optional = true }
sha2 = { version = "0.10.6", optional = true }
hex = { version = "0.4.3", optional = true }
anyhow = "1"

[features]
download-proving-keys = ["regex", "reqwest", "serde_json", "sha2", "hex"]
parallel = [
    "ark-ff/parallel",
    "decaf377/parallel",
    "ark-groth16/parallel",
    "ark-std/parallel",
    "ark-r1cs-std/parallel",
]

[[bench]]
name = "nullifier_derivation"
harness = false

[[bench]]
name = "output"
harness = false

[[bench]]
name = "delegator_vote"
harness = false

[[bench]]
name = "spend"
harness = false

[[bench]]
name = "swap"
harness = false

[[bench]]
name = "swap_claim"
harness = false

[[bench]]
name = "convert"
harness = false

[dependencies]
penumbra-num = {workspace = true, default-features = true}
penumbra-asset = {workspace = true, default-features = true}
penumbra-keys = {workspace = true, default-features = true}
decaf377 = {workspace = true, features = ["r1cs"], default-features = true}
ark-ec = {workspace = true}
ark-ff = {workspace = true, default-features = false}
ark-std = {workspace = true, default-features = false}
ark-serialize = {workspace = true}
serde = {workspace = true, features = ["derive"]}
once_cell = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
rand = {workspace = true}
num-bigint = {workspace = true}
tracing = {workspace = true}
ark-groth16 = {workspace = true, default-features = false}
ark-snark = {workspace = true}
ark-r1cs-std = {workspace = true, default-features = false}
ark-relations = {workspace = true}
sha2 = {workspace = true}
bech32 = {workspace = true}

[dev-dependencies]
penumbra-tct = {workspace = true, features = ["r1cs"], default-features = true}
criterion = {workspace = true, features = ["html_reports"]}
penumbra-dex = {workspace = true, default-features = true}
penumbra-community-pool = {workspace = true, default-features = true}
penumbra-stake = {workspace = true, default-features = true}
penumbra-shielded-pool = {workspace = true, default-features = true}
penumbra-governance = {workspace = true, default-features = true}
penumbra-fee = {workspace = true, default-features = true}
penumbra-sct = {workspace = true, default-features = true}
decaf377-fmd = {workspace = true}
decaf377-ka = {workspace = true}
decaf377-rdsa = {workspace = true}
penumbra-proof-params = {workspace = true, features = [
    "bundled-proving-keys",
    "download-proving-keys",
], default-features = true}
