[package]
name = "penumbra-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decaf377-fmd = { path ="../decaf377-fmd" }
decaf377-rdsa = { version = "0.5", git = "https://github.com/penumbra-zone/decaf377-rdsa" }
bytes = { version = "1", features = ["serde"] }
prost = "0.11"
tonic = "0.8.1"
serde = { version = "1", features = ["derive"] }
hex = "0.4"
anyhow = "1.0"
subtle-encoding = "0.5"
bech32 = "0.8"
prost-types = "0.11"
penumbra-storage = { path = "../storage", optional = true }
async-trait = "0.1.52"
tracing = "0.1"
futures = "0.3"

ibc-proto = { git = "https://github.com/cosmos/ibc-proto-rs", tag = "v0.22.0" }
ibc = { git = "https://github.com/cosmos/ibc-rs", branch = "main" }
ics23 = { git = "https://github.com/cosmos/ics23", version = "=0.8.1" }
tendermint = { git = "https://github.com/informalsystems/tendermint-rs", tag = "v0.26.0" }

# TODO(erwan): remove
num-rational = "0.4"
