{{- if .Values.only_lb_svc }}
{{- else }}
{{ $count := (.Values.network.num_validators | int) }}
{{ $val_name := printf "%s-val" (include "penumbra-network.fullname" $) }}
{{ $pvc_name := "penumbra-config" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $val_name }}
  labels:
    app: {{ $val_name }}
    app.kubernetes.io/component: genesis-validator
    app.kubernetes.io/part-of: {{ include "penumbra-network.part_of" $ }}
    {{- include "penumbra-network.labels" $ | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ $count }}
  volumeClaimTemplates:
    - metadata:
        name: {{ $pvc_name }}
        labels:
          app.kubernetes.io/component: genesis-validator
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  selector:
    matchLabels:
      app.kubernetes.io/component: genesis-validator
      {{- include "penumbra-network.selectorLabels" $ | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $val_name }}
        app.kubernetes.io/part-of: {{ include "penumbra-network.part_of" $ }}
        app.kubernetes.io/component: genesis-validator
        {{- include "penumbra-network.selectorLabels" $ | nindent 8 }}
    spec:
      # Force the pods to different k8s nodes, so that egress ip is unique per CometBFT node.
      # Effectively limits the number of Penumbra nodes to the number of k8s nodes in the cluster.
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/part-of"
                    operator: In
                    values:
                      - {{ include "penumbra-network.part_of" $ }}
                  - key: "app.kubernetes.io/component"
                    operator: In
                    values:
                      - fullnode
                      - genesis-validator
              topologyKey: kubernetes.io/hostname
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "penumbra-network.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: pd
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command:
          {{- if .Values.maintenanceMode }}
            - sleep
            - infinity
          {{- else }}
            - /usr/bin/pd
            - start
            - --grpc-bind
            - "0.0.0.0:8080"
            - --metrics-bind
            - "0.0.0.0:9000"
            - --home
            - "/penumbra-config/{{ $val_name }}/node0/pd"
          {{- end }}
          env:
            {{- toYaml $.Values.containerEnv | nindent 12 }}
          ports:
            - name: pd-grpc
              containerPort: 8080
              protocol: TCP
            - name: pd-metrics
              containerPort: 9000
              protocol: TCP
            - name: pd-abci
              containerPort: 26658
              protocol: TCP
          {{- if .Values.maintenanceMode }}
          {{- else }}
          readinessProbe:
            tcpSocket:
              port: pd-grpc
            timeoutSeconds: 5
            initialDelaySeconds: 20
          {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          securityContext:
            runAsUser: {{ .Values.maintenanceMode | ternary 0 .Values.securityContext.runAsUser }}
          volumeMounts:
            - name: {{ $pvc_name }}
              mountPath: /penumbra-config/{{ $val_name }}

        - name: cometbft
          image: "{{ $.Values.cometbft.image.repository }}:{{ $.Values.cometbft.image.tag }}"
          imagePullPolicy: {{ $.Values.cometbft.image.pullPolicy }}
          command:
          {{- if .Values.maintenanceMode }}
            - sleep
            - infinity
          {{- else }}
            - cometbft
            - start
            - --proxy_app=tcp://127.0.0.1:26658
          {{- end }}
          ports:
            - name: tm-p2p
              containerPort: 26656
              protocol: TCP
            - name: tm-rpc
              containerPort: 26657
              protocol: TCP
            - name: tm-metrics
              containerPort: 26660
              protocol: TCP
          {{- if .Values.maintenanceMode }}
          {{- else }}
          readinessProbe:
            tcpSocket:
              port: tm-rpc
            timeoutSeconds: 10
            initialDelaySeconds: 10
          {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ $pvc_name }}
              subPath: node0/cometbft
              mountPath: /cometbft
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
{{- end }}
