[package]
name = "penumbra-eddy"
version = {workspace = true}
edition = {workspace = true}

[features]
default = ["std"]
std = ["ark-ff/std", "ark-std/std"]

[dependencies]
parking_lot = {workspace = true}
decaf377 = {workspace = true}
anyhow = {workspace = true}
futures = {workspace = true}
merlin = "3"
rand_core = {workspace = true}
rand = {workspace = true}
proptest = {workspace = true}
ark-ff = {workspace = true, default-features = false}
ark-std = {workspace = true, default-features = false}
thiserror = {workspace = true}

[dev-dependencies]
tokio = {workspace = true, features = ["full"]}
