[package]
name = "penumbra-measure"
version = {workspace = true}
edition = {workspace = true}

[package.metadata.dist]
dist = false

[[bin]]
name = "measure"
path = "src/main.rs"

[dependencies]
anyhow = {workspace = true}
bytesize = "1.2"
clap = {workspace = true, features = ["derive", "env"]}
indicatif = {workspace = true}
penumbra-app = {workspace = true}
penumbra-compact-block = {workspace = true, default-features = false}
penumbra-proto = {workspace = true, features = ["rpc"], default-features = true}
serde_json = {workspace = true}
tokio = {workspace = true, features = ["full"]}
tonic = {workspace = true, features = ["tls"]}
tracing = {workspace = true}
tracing-subscriber = {workspace = true, features = ["env-filter"]}
url = {workspace = true}
