[package]
name = "penumbra-measure"
version = {workspace = true}
edition = {workspace = true}

[package.metadata.dist]
dist = false

[[bin]]
name = "measure"
path = "src/main.rs"


[dependencies]
penumbra-proto = {workspace = true, features = ["rpc"], default-features = true}
penumbra-app = {workspace = true}
penumbra-compact-block = {workspace = true, default-features = false}
tokio = {workspace = true, features = ["full"]}
tonic = {workspace = true}
anyhow = {workspace = true}
clap = {workspace = true, features = ["derive", "env"]}
tracing = {workspace = true}
tracing-subscriber = {workspace = true, features = ["env-filter"]}
url = {workspace = true}
indicatif = {workspace = true}
serde_json = {workspace = true}
bytesize = "1.2"
