[package]
name = "penumbra-shielded-pool"
version = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-ibc/component",
    "penumbra-sct/component",
    "tonic",
]
# proving-keys = ["penumbra-proof-params/proving-keys"]
default = ["std", "component"]
std = ["ark-ff/std"]
parallel = [
    "penumbra-tct/parallel",
    "ark-ff/parallel",
    "poseidon377/parallel",
    "decaf377-rdsa/parallel",
    "ark-groth16/parallel",
    "ark-r1cs-std/parallel",
    "decaf377/parallel",
    "tonic",
]
docsrs = []

[dependencies]
penumbra-proto = {workspace = true, default-features = false}
cnidarium = {workspace = true, optional = true, default-features = true}
penumbra-tct = {workspace = true, default-features = true}
penumbra-proof-params = {workspace = true, default-features = false}
penumbra-sct = {workspace = true, default-features = false}
cnidarium-component = {workspace = true, optional = true, default-features = true}
penumbra-ibc = {workspace = true, default-features = false}
penumbra-asset = {workspace = true, default-features = false}
penumbra-num = {workspace = true, default-features = false}
penumbra-keys = {workspace = true, default-features = false}
penumbra-txhash = {workspace = true, default-features = false}
decaf377-ka = {workspace = true}
decaf377-fmd = {workspace = true}
ibc-types = {workspace = true, default-features = false}
decaf377-rdsa = {workspace = true}
decaf377 = {workspace = true, features = ["r1cs"], default-features = true}
poseidon377 = {workspace = true, features = ["r1cs"]}
base64 = {workspace = true}
thiserror = {workspace = true}
chacha20poly1305 = {workspace = true}
ark-r1cs-std = {workspace = true, default-features = false}
ark-relations = {workspace = true}
ark-ff = {workspace = true, default-features = false}
ark-serialize = {workspace = true}
ark-groth16 = {workspace = true, default-features = false}
ark-snark = {workspace = true}
metrics = {workspace = true}
prost = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
tracing = {workspace = true}
anyhow = {workspace = true}
async-trait = {workspace = true}
tendermint = {workspace = true}
blake2b_simd = {workspace = true}
bytes = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
rand = {workspace = true}
im = {workspace = true}
once_cell = {workspace = true}
hex = {workspace = true}
tonic = {workspace = true, optional = true}

[dev-dependencies]
proptest = {workspace = true}
