[package]
name = "penumbra-stake"
version = "0.52.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = [
    "penumbra-component",
    "penumbra-storage",
    "penumbra-proto/penumbra-storage",
    "penumbra-chain/component",
    "penumbra-sct/component"
]
proving-keys = ["penumbra-proof-params/proving-keys"]
default = ["component", "proving-keys"]
docsrs = []

[dependencies]
# Workspace dependencies
penumbra-crypto = { path = "../../crypto" }
penumbra-component = { path = "../component", optional = true }
penumbra-storage = { path = "../../storage", optional = true }
penumbra-shielded-pool = { path = "../shielded-pool" }
penumbra-sct = { path = "../sct", default-features = false}
penumbra-dao = { path = "../dao", default-features = false}
penumbra-proto = { path = "../../proto" }
penumbra-chain = { path = "../../chain", default-features = false }
penumbra-tct = { path = "../../tct" }
penumbra-proof-params = { path = "../../proof-params" }

# Penumbra dependencies
tokio = { version = "1.21.1", features = ["full", "tracing"] }
async-trait = "0.1.52"
anyhow = "1"
tracing = "0.1"
blake2b_simd = "0.5"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_with = "2.2"
metrics = "0.19.0"
sha2 = "0.9"
serde_json = "1"
serde_unit_struct = "0.1"
bech32 = "0.8"
im = "15.1.0"
regex = "1.5"
once_cell = "1.8"
bitvec = "1"
hex = "0.4"
base64 = "0.20"
tempfile = "3.3.0"
prost = "0.11"
rand_chacha = "0.3"
parking_lot = "0.12"
tendermint = "0.29.0"

[dev-dependencies]
ed25519-consensus = "2"
rand_core = "0.6"
penumbra-tct = { path = "../../tct" }
rand_chacha = "0.3"
penumbra-transaction = { path = "../../transaction", features = ["parallel"] }
tracing-subscriber = "0.3"

[build-dependencies]
vergen = "5"
