---
# Values file for devnet deploys.
ingress:
  enabled: true
  hosts:
    # The Tendermint RPC port.
    rpc: rpc.devnet.penumbra.zone
    # The pd gRPC port.
    grpc: grpc.devnet.penumbra.zone
    # The Grafana HTTP web interface, for viewing dashboards.
    grafana: grafana.devnet.penumbra.zone
