[package]
name = "penumbra-proof-params"
version = {workspace = true}
edition = {workspace = true}

[build-dependencies]
regex = { version = "1", optional = true }
reqwest = { version = "0.11.14", optional = true, features = [
    "blocking",
    "json",
] }
serde_json = { version = "1", optional = true }
sha2 = { version = "0.10.6", optional = true }
hex = { version = "0.4.3", optional = true }
anyhow = "1"

[features]
bundled-proving-keys = []
download-proving-keys = [
    "regex",
    "reqwest",
    "serde_json",
    "sha2",
    "hex",
    "bundled-proving-keys",
]
parallel = [
    "ark-ff/parallel",
    "decaf377/parallel",
    "ark-groth16/parallel",
    "ark-std/parallel",
    "ark-r1cs-std/parallel",
]

[dependencies]
decaf377 = {workspace = true, features = ["r1cs"], default-features = true}
anyhow = {workspace = true}
ark-ec = {workspace = true}
ark-ff = {workspace = true, default-features = false}
ark-std = {workspace = true, default-features = false}
ark-serialize = {workspace = true}
serde = {workspace = true, features = ["derive"]}
once_cell = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
rand = {workspace = true}
num-bigint = {workspace = true}
tracing = {workspace = true}
ark-groth16 = {workspace = true, default-features = false}
ark-snark = {workspace = true}
ark-r1cs-std = {workspace = true, default-features = false}
ark-relations = {workspace = true}
sha2 = {workspace = true}
bech32 = {workspace = true}
lazy_static = "1.4.0"
