[package]
name = "penumbra-proof-params"
version = "0.64.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Git deps
decaf377 = { version = "0.5", features = ["r1cs"] }

# Crates.io deps
anyhow = "1"
ark-ec = "0.4.2"
ark-ff = { version = "0.4", default-features = false }
ark-std = { version = "0.4", default-features = false }
ark-serialize = "0.4"
serde = { version = "1", features = ["derive"] }
once_cell = "1.8"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
# only needed because ark-ff doesn't display correctly
num-bigint = "0.4"
tracing = "0.1"
ark-groth16 = { version = "0.4", default-features = false }
ark-snark = "0.4"
ark-r1cs-std = { version = "0.4", default-features = false }
ark-relations = "0.4"
sha2 = "0.10.1"
bech32 = "0.8.1"
lazy_static = "1.4.0"

[build-dependencies]
regex = { version = "1", optional = true }
reqwest = { version = "0.11.14", optional = true, features = [
    "blocking",
    "json",
] }
serde_json = { version = "1", optional = true }
sha2 = { version = "0.10.6", optional = true }
hex = { version = "0.4.3", optional = true }
anyhow = "1"

[features]
bundled-proving-keys = []
download-proving-keys = [
    "regex",
    "reqwest",
    "serde_json",
    "sha2",
    "hex",
    "bundled-proving-keys",
]
parallel = [
    "ark-ff/parallel",
    "decaf377/parallel",
    "ark-groth16/parallel",
    "ark-std/parallel",
    "ark-r1cs-std/parallel",
]
