[package]
name = "penumbra-wallet-next"
version = "0.1.0"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "The wallet software for the Penumbra Zone"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../proto" }
penumbra-chain = { path = "../chain" }
penumbra-crypto = { path = "../crypto" }
penumbra-stake = { path = "../stake" }
penumbra-transaction = { path = "../transaction" }
penumbra-tct = { path = "../tct" }
penumbra-view = { path = "../view" }
penumbra-custody = { path = "../custody" }

# External dependencies
bytes = "1"
bincode = "1.3.3"
tokio = { version = "1", features = ["full"]}
tower = { version = "0.4", features = ["full"]}
tonic = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"
pin-project = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1.11", features = ["hex"] }
anyhow = "1"
hex = "0.4"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
