apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ include "penumbra-metrics.fullname" . }}
  labels:
    {{- include "penumbra-metrics.labels" . | nindent 4 }}
data:
  grafana_datasources.yml: |
    datasources:
    - name: 'Prometheus'
      type: 'prometheus'
      access: 'browser'
      url: 'http://localhost:9090'
      is_default: true
      editable: false
  prometheus_scrape_configs: |
    scrape_configs:
{{ $count := (.Values.scrape_configs.numFullNodes | int) }}
{{ range $i,$e := until $count }}
{{ $fn_name := printf $.Values.scrape_configs.fmtFullNodeSvc $i }}

      - job_name: 'Tendermint Fullnode {{ $i }}'
        scrape_interval: 10s
        scheme: http
        metrics_path: metrics
        static_configs:
          - targets: ['{{ $fn_name }}:26660']

      - job_name: 'Penumbra Daemon Fullnode {{ $i }}'
        scrape_interval: 10s
        scheme: http
        metrics_path: metrics
        static_configs:
          - targets: ['{{ $fn_name }}:9000']
{{ end }}
{{ $count := (.Values.scrape_configs.numValidators | int) }}
{{ range $i,$e := until $count }}
{{ $val_name := printf $.Values.scrape_configs.fmtValidatorSvc $i }}
      - job_name: 'Tendermint Validator {{ $i }}'
        scrape_interval: 10s
        scheme: http
        metrics_path: metrics
        static_configs:
          - targets: ['{{ $val_name }}:26660']
      - job_name: 'Penumbra Daemon Validator {{ $i }}'
        scrape_interval: 10s
        scheme: http
        metrics_path: metrics
        static_configs:
          - targets: ['{{ $val_name }}:9000']
{{ end }}
