apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ include "penumbra-metrics.fullname" . }}
  labels:
    {{- include "penumbra-metrics.labels" . | nindent 4 }}
data:
  grafana_datasources.yml: |
    datasources:
    - name: 'Prometheus'
      type: 'prometheus'
      access: 'browser'
      url: 'http://localhost:9090'
      is_default: true
      editable: false
  prometheus_scrape_configs: |
    scrape_configs:

      - job_name: 'Penumbra Fullnode'
        scrape_interval: 10s
        scheme: http
        metrics_path: metrics
        static_configs:
{{ $count := (.Values.scrape_configs.numFullNodes | int) }}
{{ range $i,$e := until $count }}
          - targets:
{{ $fn_name := printf $.Values.scrape_configs.fmtFullNodeSvc $i }}
            - '{{ $fn_name }}:9000'
            - '{{ $fn_name }}:26660'
{{ end }}

      - job_name: 'Penumbra Validator'
        scrape_interval: 10s
        scheme: http
        metrics_path: metrics
        static_configs:
          - targets:
{{ $count := (.Values.scrape_configs.numValidators | int) }}
{{ range $i,$e := until $count }}
{{ $val_name := printf $.Values.scrape_configs.fmtValidatorSvc $i }}
            - '{{ $val_name }}:9000'
            - '{{ $val_name }}:26660'
{{ end }}
