[package]
name = "penumbra-tct"
version = "0.55.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penumbra-proto = { path = "../../proto/" }

derivative = "2"
once_cell = "1"
blake2b_simd = "1"
hex = "0.4"
hash_hasher = "2"
thiserror = "1"
serde = { version = "1.0", features = ["derive", "rc"] }
parking_lot = "0.12"
ark-ff = { version = "0.4", default_features = false }
ark-serialize = "0.4"
poseidon377 = { version = "0.6", features = ["r1cs"] }
decaf377 = { version = "0.4" }
tracing = { version = "0.1" }
async-trait = { version = "0.1" }
futures = "0.3"
ark-ed-on-bls12-377 = "0.4"
rand = "0.8"
im = { version = "^15.1.0", features = ["serde"] } # IMPORTANT: an OrdMap correctness bug was fixed in 15.1.0, as well as a performance improvement to `union`
ark-relations = {version = "0.4", optional=true }
ark-r1cs-std = {version = "0.4", optional=true, default-features = false }

# Dependencies for random testing
proptest = { version = "1", optional = true }
proptest-derive = { version = "0.3", optional = true }

[features]
internal = []
arbitrary = ["proptest", "proptest-derive"]
r1cs = ["ark-r1cs-std", "ark-relations", "decaf377/r1cs", "poseidon377/r1cs"]
parallel = ["ark-r1cs-std/parallel", "ark-ff/parallel", "decaf377/parallel", "poseidon377/parallel"]

[dev-dependencies]
static_assertions = "1"
proptest = "1"
proptest-derive = "0.3"
serde_json = "1"
