[package]
name = "pd"
version = "0.62.0"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "The node software for the Penumbra Zone"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false
# Pin a MSRV. Anything more recent than this value is OK.
# If a lower version is used for build, the build will fail.
rust-version = "1.65"

[features]
std = ["ibc-types/std"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../../proto" }
penumbra-storage = { path = "../../storage", features = ["migration"] }
penumbra-asset = { path = "../../core/asset" }
penumbra-keys = { path = "../../core/keys" }
penumbra-shielded-pool = { path = "../../core/component/shielded-pool", features = [
    "parallel",
] }
penumbra-stake = { path = "../../core/component/stake", features = [
    "parallel",
] }
penumbra-sct = { path = "../../core/component/sct" }
penumbra-dex = { path = "../../core/component/dex", features = ["parallel"] }
penumbra-governance = { path = "../../core/component/governance", features = [
    "parallel",
] }
penumbra-ibc = { path = "../../core/component/ibc", features = ["rpc"] }
penumbra-compact-block = { path = "../../core/component/compact-block" }
penumbra-chain = { path = "../../core/component/chain" }
penumbra-transaction = { path = "../../core/transaction" }
penumbra-app = { path = "../../core/app" }
penumbra-wallet = { path = "../../wallet" }
penumbra-tower-trace = { path = "../../util/tower-trace" }
penumbra-tendermint-proxy = { path = "../../util/tendermint-proxy" }

# Penumbra dependencies
decaf377 = { version = "0.5", features = ["parallel"] }
decaf377-rdsa = { version = "0.7" }
tower-abci = "0.10.0"
jmt = "0.9"
tower-actor = "0.1.0"

# External dependencies
tendermint-config = "0.34.0"
tendermint-proto = "0.34.0"
tendermint = "0.34.0"
tendermint-light-client-verifier = "0.34.0"
ibc-types = { version = "0.6.3" }

ibc-proto = { version = "0.37.0", default-features = false, features = ["server"] }
prost = "0.11"
toml = "0.5"
# We don't need this crate at all, but its upstream published a breaking change as
# 0.7.1 (also prost-related), and depending on an exact version here will exclude
# the bad update until it's yanked.
ics23 = "0.11.0"

pin-project-lite = "0.2.9"
ark-ff = { version = "0.4" }
async-stream = "0.2"
bincode = "1.3.3"
blake2b_simd = "0.5"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
csv = "1.1"
directories = "4.0"
tokio = { version = "1.22", features = ["full"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["compat"] }
tower = { version = "0.4", features = ["full"] }
tower-service = "0.3.2"
tracing = "0.1"
regex = "1.5"
reqwest = { version = "0.11", features = ["json"] }
prost-types = "0.11"
pbjson-types = "0.5"
tonic = "0.9"
tonic-web = "0.9.0"
tonic-reflection = "0.9.0"
tracing-subscriber = { version = "0.3", features = ["env-filter", "ansi"] }
url = "2"
pin-project = "1"
futures = "0.3"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1.11", features = ["hex"] }
sha2 = "0.9"
anyhow = "1"
hex = "0.4"
rand = "0.8"
rand_chacha = "0.3.1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
metrics = "0.19.0"
metrics-exporter-prometheus = { version = "0.10.0", features = [
    "http-listener",
] }
http = "0.2"
ed25519-consensus = "2"

async-trait = "0.1.52"
tendermint-rpc = { version = "0.34.0", features = ["http-client"] }
once_cell = "1.7.2"
rocksdb = "0.21.0"
tempfile = "3.3.0"
base64 = "0.20"
console-subscriber = "0.1.8"
metrics-tracing-context = "0.11.0"
metrics-util = "0.13"
clap = { version = "3", features = ["derive", "env"] }
rustls-acme = "0.6"
atty = "0.2"
fs_extra = "1.3.0"

[build-dependencies]
vergen = "5"
anyhow = "1"

[package.metadata.dist]
dist = true

[package.metadata.release]
# Update the guide docs to use the most recent version, to reduce tedium.
# Preview the changes with `cargo release replace`.
pre-release-replacements = [
    { file = "../../../docs/guide/src/pcli/install.md", search = "(cd penumbra && git fetch && git checkout) .*", replace = "$1 {{tag_name}}", exactly = 1 },
    { file = "../../../docs/guide/src/pcli/update.md", search = "(cd penumbra && git fetch && git checkout) .*", replace = "$1 {{tag_name}}", exactly = 1 },
]
