[package]
name = "penumbra-transaction"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace deps
decaf377-ka = { path = "../decaf377-ka/" }
decaf377-fmd = { path = "../decaf377-fmd/" }
penumbra-proto = { path = "../proto/" }
penumbra-crypto = { path = "../crypto/" }
penumbra-chain = { path = "../chain/", default-features = false }
penumbra-tct = { path = "../tct" }
penumbra-proof-params = { path = "../proof-params/", features = ["proving-keys"] }

# Git deps
decaf377 = "0.3"
decaf377-rdsa = { version = "0.5", git = "https://github.com/penumbra-zone/decaf377-rdsa" }
poseidon377 = { git = "https://github.com/penumbra-zone/poseidon377", branch = "main" }
ibc = "0.29"
ibc-proto = { version = "0.26", features = ["std"] }

# Crates.io deps
base64 = "0.21"
ark-ff = { version = "0.3", default_features = false }
ark-serialize = "0.3"
regex = "1.5"
sha2 = "0.9"
bech32 = "0.8.1"
aes = "0.7"
anyhow = "1"
thiserror = "1"
bytes = "1"
derivative = "2.2"
hex = "0.4"
blake2b_simd = "0.5"
serde = { version = "1", features = ["derive"] }
once_cell = "1.8"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
chacha20poly1305 = "0.9.0"
pbjson-types = "0.5"
# only needed because ark-ff doesn't display correctly
num-bigint = "0.4"
serde_json = "1"
tracing = "0.1"
tokio = { version = "1.21.1", features = ["full"], optional = true }
clap = { version = "3", features = ["derive"], optional = true }

[dev-dependencies]
proptest = "1"
proptest-derive = "0.3"
serde_json = "1"

[features]
default = ["std"]
std = ["ark-ff/std"]
parallel = ["tokio", "penumbra-crypto/parallel"]