apiVersion: v2
name: penumbra
description: Run Penumbra nodes and/or validators

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.

# Pre-mainnet, we set this to a tag name for the given testnet, e.g. '036-iocaste.2'.
# Container images are automatically tagged for each testnet; we can also use "latest"
# for the HEAD of main branch in the penumbra git repository.
appVersion: "037-megaclite.1"
