---
{{- /*
The database schema file for CometBFT is required for event indexing via postgres.
See more info at "https://docs.cometbft.com/v0.37/app-dev/indexing-transactions#postgresql".
*/}}
{{- if eq .Values.cometbft.config.indexer "psql" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "penumbra-node.fullname" . }}-postgres-schema
data:
  postgres-cometbft-schema.sql: {{ .Files.Get (printf "files/postgres-cometbft-schema.sql") | quote }}
{{ end }}
