{{- if .Values.persistence.enabled }}
{{ $count := (.Values.nodes | len | int) }}
{{ range $i,$e := until $count }}
{{ $fn_name := printf "%s-fn-%d" $.Release.Name $i }}
{{ $pvc_name := printf "%s-config" $fn_name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvc_name }}
  labels:
    {{- include "penumbra-node.labels" $ | nindent 4 }}
spec:
  accessModes: {{ $.Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}
  {{- if $.Values.persistence.storageClassName }}
  storageClassName: {{ $.Values.persistence.storageClassName }}
  {{- end }}
{{- end }}
{{- end }}
