{{- if .Values.persistence.enabled }}
{{ $count := (.Values.nodes | len | int) }}
{{ range $i,$e := until $count }}
{{ $fn_name := printf "%s-fn-%d" $.Release.Name $i }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fn_name }}-config
  labels:
    {{- include "penumbra-node.labels" $ | nindent 4 }}
spec:
  accessModes: {{ $.Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}
  {{- if $.Values.persistence.storageClassName }}
  storageClassName: {{ $.Values.persistence.storageClassName }}
  {{- end }}
---
{{- if eq $.Values.cometbft.config.indexer "psql" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fn_name }}-db
  labels:
    {{- include "penumbra-node.labels" $ | nindent 4 }}
spec:
  accessModes: {{ $.Values.persistence.accessModes }}
  resources:
    requests:
      # Storage for db is <1% of storage for node state.
      # We could dynamically compute that based on persistence size,
      # but it's also fine if we just hardcode the value for now.
      storage: 2G
  {{- if $.Values.persistence.storageClassName }}
  storageClassName: {{ $.Values.persistence.storageClassName }}
  {{- end }}
{{- end }}

{{- end }}
{{- end }}
