{{ $count := (.Values.nodes | len | int) }}
{{ range $i,$e := until $count }}
{{- /*
We set the service names to include the string "-fn"
for compatibility reasons: doing so allows us to reuse pre-existing
services and their associated IPs.
*/}}
{{ $fn_name := printf "%s-%d" $.Release.Name $i }}
{{ $rpc_svc_name := printf "%s-fn-%d" $.Release.Name $i }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $rpc_svc_name }}
  labels:
    app.kubernetes.io/component: rpc
    {{- include "penumbra-node.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: pd-grpc
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: pd-metrics
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: tm-rpc
      port: 26657
      targetPort: 26657
      protocol: TCP
    - name: tm-metrics
      port: 26660
      targetPort: 26660
      protocol: TCP
  {{- if eq $.Values.cometbft.config.indexer "psql" }}
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ $fn_name }}
    {{- include "penumbra-node.selectorLabels" $ | nindent 4 }}

{{- if (index $.Values.nodes $i).external_address -}}
{{- /*
We only configure an external LoadBalancer service for p2p
if an IP has been provided. This logic is awkward because we must
first create the LB to get an IP, then use that IP in the config
for CometBFT. Using an operator pattern would enable us to sidestep this.
*/}}
{{ $p2p_svc_name := printf "%s-fn-%d-p2p" $.Release.Name $i }}
---
apiVersion: v1
kind: Service
metadata:
  # P2P service is a LoadBalancer with externalTrafficPolicy=Local by default,
  # because no other networking setup makes sense. We need the source IP preserved
  # for CometBFT P2P to work.
  name: {{ $p2p_svc_name }}
  {{- if $.Values.preserve_lb_svc }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
  labels:
    app.kubernetes.io/component: p2p
    {{- include "penumbra-node.labels" $ | nindent 4 }}
spec:
  externalTrafficPolicy: Local
  ports:
  - name: tm-p2p
    port: 26656
    protocol: TCP
    targetPort: 26656
  selector:
    statefulset.kubernetes.io/pod-name: {{ $fn_name }}
    {{- include "penumbra-node.selectorLabels" $ | nindent 4 }}
  type: LoadBalancer
{{ end }}
{{ end }}
