[package]
name = "penumbra-proto"
version = {workspace = true}
edition = {workspace = true}

[build-dependencies]
anyhow = "1"

[features]
rpc = ["dep:tonic", "ibc-proto/client"]
box-grpc = ["dep:http-body", "dep:tonic", "dep:tower"]
cnidarium = ["dep:cnidarium"]

[dependencies]
anyhow = {workspace = true}
async-trait = {workspace = true}
bech32 = {workspace = true}
bytes = {workspace = true, features = ["serde"]}
chrono = {workspace = true, default-features = false, features = ["serde"]}
cnidarium = {workspace = true, optional = true, default-features = true}
decaf377-fmd = {workspace = true}
decaf377-rdsa = {workspace = true}
futures = {workspace = true}
hex = {workspace = true}
http-body = {workspace = true, optional = true}
ibc-types = {workspace = true, features = ["std"], default-features = true}
ics23 = {workspace = true}
pbjson = {workspace = true}
pbjson-types = {workspace = true}
pin-project = {workspace = true}
prost = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
subtle-encoding = "0.5"
tendermint = {workspace = true}
tendermint-proto = {workspace = true}
tendermint-rpc = {workspace = true, features = ["http-client"]}
thiserror = {workspace = true}
tonic = {workspace = true, optional = true}
tower = {workspace = true, features = ["full"], optional = true}
tracing = {workspace = true}

[dependencies.ibc-proto]
workspace = true
default-features = false
features = [
    "std",
    "serde",
]
