---
releases:
  - name: penumbra-testnet
    chart: ../charts/penumbra-network
    values:
      - persistence:
          enabled: true
          size: 300G
      - preserve_lb_svc: true
      - only_lb_svc: false
      - image:
          tag: latest
      - network:
          preserve_chain_id: true
          external_addresses: "34.68.222.252:26656,35.226.255.25:26656"
      - part_of: penumbra-testnet
      # Sidecar vars file for storing external ips. The "penumbra-network" chart
      # doesn't read these vars, but the "get-lb-ips" script writes them there,
      # and they've been manually duplicated above in the values.network.external_addresses field.
      - vars/penumbra-testnet-ips.yml

  - name: penumbra-testnet-nodes
    chart: ../charts/penumbra-node
    needs:
      - penumbra-testnet
    values:
      - ingressRoute:
          enabled: true
          hosts:
            pd: grpc.testnet.penumbra.zone
            tm: rpc.testnet.penumbra.zone
          secretName: penumbra-testnet-wildcard
      - preserve_lb_svc: true
      - only_lb_svc: false
      - image:
          tag: latest
      # Communicate intra-cluster to the private validator rpc address.
      - penumbra_bootstrap_node_cometbft_rpc_url: "http://penumbra-testnet-val-0:26657"
      - persistence:
          enabled: true
          size: 300G
      - part_of: penumbra-testnet
      # Node config info, including ip address, monikers, and seed-mode status.
      - vars/penumbra-testnet-nodes-ips.yml

  - name: penumbra-testnet-metrics
    chart: ../charts/penumbra-metrics
    values:
      - ingressRoute:
          enabled: true
          hosts:
            grafana: grafana.testnet.penumbra.zone
          secretName: penumbra-testnet-wildcard
      - scrape_configs:
          # Must match settings from "penumbra-node" chart
          numFullNodes: 4
          fmtFullNodeSvc: "penumbra-testnet-nodes-fn-%d"
          # Must match settings from "penumbra-network" chart
          numValidators: 2
          fmtValidatorSvc: "penumbra-testnet-val-%d"
      - image:
          tag: latest
      - persistence:
          enabled: true
          size: 20G

  - name: penumbra-testnet-cuiloa-node
    chart: ../charts/penumbra-node
    needs:
      - penumbra-testnet
      # It's not strictly necessary to wait for node deploys, but doing so allows us to exercise
      # the public HTTPS RPC endpoint for joining, which is nice.
      - penumbra-testnet-nodes
    values:
      - penumbra_bootstrap_node_cometbft_rpc_url: "https://rpc.testnet.penumbra.zone"
      - ingressRoute:
          enabled: false
      - image:
          tag: latest
      - persistence:
          enabled: true
          size: 300G
      - cometbft:
          config:
            indexer: psql
      - part_of: penumbra-testnet
      - nodes:
        - moniker: cuiloa

  - name: penumbra-testnet-dex-explorer-node
    chart: ../charts/penumbra-node
    needs:
      - penumbra-testnet
      - penumbra-testnet-nodes
    values:
      - penumbra_bootstrap_node_cometbft_rpc_url: "https://rpc.testnet.penumbra.zone"
      - ingressRoute:
          enabled: false
      - image:
          tag: latest
      - persistence:
          enabled: true
          size: 300G
      - cometbft:
          config:
            indexer: psql
      - part_of: penumbra-testnet
      - nodes:
        - moniker: dex-explorer
