---
releases:
  - name: penumbra-preview
    chart: ../charts/penumbra-network
    values:
      - persistence:
          enabled: true
          size: 20G
      - preserve_lb_svc: true
      - only_lb_svc: false
      - image:
          tag: main
      - network:
          external_addresses: "35.192.203.35:26656,34.28.180.178:26656"
      - part_of: penumbra-preview
      # Sidecar vars file for storing external ips. The "penumbra-network" chart
      # doesn't read these vars, but the "get-lb-ips" script writes them there,
      # and they've been manually duplicated above in the values.network.external_addresses field.
      - vars/penumbra-preview-ips.yml

  - name: penumbra-preview-nodes
    chart: ../charts/penumbra-node
    needs:
      - penumbra-preview
    values:
      - ingressRoute:
          enabled: true
          hosts:
            pd: grpc.testnet-preview.penumbra.zone
            tm: rpc.testnet-preview.penumbra.zone
          secretName: penumbra-preview-wildcard
      - preserve_lb_svc: true
      - only_lb_svc: false
      - image:
          tag: main
      # Communicate intra-cluster to the private validator rpc address.
      - penumbra_bootstrap_node_cometbft_rpc_url: "http://penumbra-preview-val-0:26657"
      - persistence:
          enabled: true
          size: 20G
      - part_of: penumbra-preview
      # Node config info, including ip address, monikers, and seed-mode status.
      - vars/penumbra-preview-nodes-ips.yml

  - name: penumbra-preview-metrics
    chart: ../charts/penumbra-metrics
    values:
      - ingressRoute:
          enabled: true
          hosts:
            grafana: grafana.testnet-preview.penumbra.zone
          secretName: penumbra-preview-wildcard
      - scrape_configs:
          # Must match settings from "penumbra-node" chart
          numFullNodes: 4
          fmtFullNodeSvc: "penumbra-preview-nodes-fn-%d"
          # Must match settings from "penumbra-network" chart
          numValidators: 2
          fmtValidatorSvc: "penumbra-preview-val-%d"
      - image:
          tag: main
      - persistence:
          enabled: true
          size: 10G

  - name: penumbra-preview-cuiloa-node
    chart: ../charts/penumbra-node
    needs:
      - penumbra-preview
      # It's not strictly necessary to wait for node deploys, but doing so allows us to exercise
      # the public HTTPS RPC endpoint for joining, which is nice.
      - penumbra-preview-nodes
    values:
      - penumbra_bootstrap_node_cometbft_rpc_url: "https://rpc.testnet-preview.penumbra.zone"
      - ingressRoute:
          enabled: false
      - image:
          tag: main
      - persistence:
          enabled: true
          size: 20G
      - cometbft:
          config:
            indexer: psql
      - part_of: penumbra-preview
      - nodes:
        - moniker: cuiloa

  - name: penumbra-preview-dex-explorer-node
    chart: ../charts/penumbra-node
    needs:
      - penumbra-preview
      # It's not strictly necessary to wait for node deploys, but doing so allows us to exercise
      # the public HTTPS RPC endpoint for joining, which is nice.
      - penumbra-preview-nodes
    values:
      - penumbra_bootstrap_node_cometbft_rpc_url: "https://rpc.testnet-preview.penumbra.zone"
      - ingressRoute:
          enabled: false
      - image:
          tag: main
      - persistence:
          enabled: true
          size: 20G
      - cometbft:
          config:
            indexer: psql
      - part_of: penumbra-preview
      - nodes:
        - moniker: dex-explorer
