[package]
name = "pcli"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
description = "The command-line interface for the Penumbra Zone"
repository = {workspace = true}
homepage = {workspace = true}
license = {workspace = true}
publish = false

[package.metadata.dist]
dist = true

[features]
default = ["std", "parallel", "download-proving-keys"]
download-proving-keys = ["penumbra-proof-params/download-proving-keys"]
sct-divergence-check = ["penumbra-view/sct-divergence-check"]
std = ["ark-ff/std", "ibc-types/std"]
parallel = [
    "penumbra-proof-params/parallel",
    "decaf377/parallel",
    "penumbra-shielded-pool/parallel",
    "penumbra-dex/parallel",
    "penumbra-governance/parallel",
    "penumbra-stake/parallel",
    "penumbra-transaction/parallel",
    "penumbra-wallet/parallel",
    "penumbra-proof-setup/parallel",
]

[dependencies]
penumbra-proto = {workspace = true, features = ["rpc", "box-grpc"], default-features = true}
penumbra-tct = {workspace = true, default-features = true}
penumbra-num = {workspace = true, default-features = false}
penumbra-asset = {workspace = true, default-features = false}
penumbra-keys = {workspace = true, default-features = false}
penumbra-shielded-pool = {workspace = true, default-features = false}
penumbra-governance = {workspace = true, default-features = false}
penumbra-stake = {workspace = true, default-features = false}
penumbra-sct = {workspace = true, default-features = false}
penumbra-fee = {workspace = true, default-features = false}
penumbra-dex = {workspace = true, default-features = false}
penumbra-community-pool = {workspace = true, default-features = false}
penumbra-ibc = {workspace = true, default-features = false}
penumbra-compact-block = {workspace = true, default-features = false}
penumbra-transaction = {workspace = true, default-features = true}
penumbra-proof-setup = {workspace = true}
penumbra-app = {workspace = true}
penumbra-wallet = { path = "../../wallet" }
penumbra-custody = {workspace = true}
penumbra-view = {workspace = true}
decaf377 = {workspace = true, default-features = true}
decaf377-rdsa = {workspace = true}
tendermint = {workspace = true, features = ["rust-crypto"], default-features = true}
jmt = {workspace = true}
ibc-types = {workspace = true, features = ["std", "with_serde"], default-features = true}
ibc-proto = {workspace = true, default-features = true}
ark-ff = {workspace = true, default-features = false}
atty = {workspace = true}
ed25519-consensus = {workspace = true}
futures = {workspace = true}
async-stream = {workspace = true}
bincode = {workspace = true}
blake2b_simd = {workspace = true}
base64 = {workspace = true}
simple-base64 = "0.23"
bytes = {workspace = true}
comfy-table = "5"
directories = {workspace = true}
tokio = {workspace = true, features = ["full"]}
tokio-stream = {workspace = true}
tokio-util = {workspace = true}
tower = {workspace = true, features = ["full"]}
tracing = {workspace = true}
tonic = {workspace = true, features = ["tls-webpki-roots", "tls"]}
tracing-subscriber = {workspace = true, features = ["env-filter", "ansi"]}
pin-project = {workspace = true}
serde_json = {workspace = true}
serde = {workspace = true, features = ["derive"]}
regex = {workspace = true}
serde_with = {workspace = true, features = ["hex"]}
sha2 = {workspace = true}
anyhow = {workspace = true}
hex = {workspace = true}
rand = {workspace = true}
rand_chacha = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
rpassword = "7"
indicatif = {workspace = true}
http-body = {workspace = true}
clap = {workspace = true, features = ["derive", "env"]}
camino = {workspace = true}
url = {workspace = true, features = ["serde"]}
colored_json = "2.1"
toml = {workspace = true, features = ["preserve_order"]}
once_cell = {workspace = true}
ndarray = "0.15.6"
dialoguer = "0.10.4"

[dev-dependencies]
assert_cmd = {workspace = true}
predicates = "2.1"
tempfile = {workspace = true}
regex = {workspace = true}
penumbra-governance = {workspace = true, default-features = false}
penumbra-proof-params = {workspace = true, features = [
    "bundled-proving-keys",
    "download-proving-keys",
], default-features = true}
