[package]
name = "penumbra-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../proto" }
penumbra-crypto = { path = "../crypto" }
penumbra-transaction = { path = "../transaction" }
penumbra-stake = { path = "../stake" }

# Penumbra dependencies
decaf377 = { git = "https://github.com/penumbra-zone/decaf377" }

# Crates.io deps
ark-ff = "0.3"
anyhow = "1"
bytes = "1"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
