[package]
name = "penumbra-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../proto", features = ["penumbra-storage"] }
penumbra-storage = { path = "../storage" }
penumbra-crypto = { path = "../crypto" }
penumbra-transaction = { path = "../transaction" }
penumbra-tct = { path = "../tct" }

# Penumbra dependencies
decaf377 = { git = "https://github.com/penumbra-zone/decaf377" }
# jmt = { git = "https://github.com/penumbra-zone/jellyfish-merkle.git", branch = "newmain" }
jmt = { path = "../../jmt" }

tendermint = { git = "https://github.com/informalsystems/tendermint-rs", tag = "v0.26.0" }
ibc = { git = "https://github.com/cosmos/ibc-rs", tag = "v0.23.0" }
ics23 = { version = "=0.8.1" }

# Crates.io deps
ark-ff = "0.3"
anyhow = "1"
bytes = "1"
hex = "0.4"
once_cell = "1.8"
sha2 = "0.9"
serde = { version = "1", features = ["derive"] }
async-trait = "0.1.52"
tracing = "0.1"
tonic = "0.8.1"
num-rational = "0.4"
