[package]
name = "penumbra-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../proto" }
penumbra-crypto = { path = "../crypto" }
penumbra-transaction = { path = "../transaction" }


# Crates.io deps
anyhow = "1"
bytes = "1"
serde = { version = "1", features = ["derive"] }
