[package]
name = "penumbra-effecthash"
version = "0.64.1"
edition = "2021"

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../../proto", default-features = false }
anyhow = "1"
hex = "0.4"
