[package]
name = "pclientd"
version = {workspace = true}
edition = {workspace = true}

[features]
default = ["std", "download-proving-keys"]
std = ["ibc-types/std"]
sct-divergence-check = ["penumbra-view/sct-divergence-check"]
# Enable to use rayon parallelism for crypto operations
parallel = ["penumbra-transaction/parallel"]
download-proving-keys = ["penumbra-proof-params/download-proving-keys"]

[dependencies]
penumbra-proto = {workspace = true, features = ["rpc"], default-features = true}
penumbra-tct = {workspace = true, default-features = true}
penumbra-asset = {workspace = true, default-features = true}
penumbra-keys = {workspace = true, default-features = true}
penumbra-transaction = {workspace = true, default-features = true}
penumbra-app = {workspace = true}
penumbra-custody = {workspace = true}
penumbra-view = {workspace = true}
tokio = {workspace = true, features = ["full"]}
tokio-stream = {workspace = true, features = ["sync"]}
anyhow = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
rand = {workspace = true}
serde_json = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_with = {workspace = true, features = ["hex"]}
tracing = {workspace = true}
tracing-subscriber = {workspace = true, features = ["env-filter"]}
url = {workspace = true, features = ["serde"]}
http = {workspace = true}
http-body = {workspace = true}
tower = {workspace = true}
tonic = {workspace = true}
tonic-web = {workspace = true}
tonic-reflection = {workspace = true}
bytes = {workspace = true, features = ["serde"]}
prost = {workspace = true}
futures = {workspace = true}
hex = {workspace = true}
metrics = {workspace = true}
async-stream = {workspace = true}
parking_lot = {workspace = true}
clap = {workspace = true, features = ["derive", "env"]}
camino = {workspace = true}
async-trait = {workspace = true}
tendermint = {workspace = true}
sha2 = {workspace = true}
toml = {workspace = true}
ed25519-consensus = {workspace = true}
atty = {workspace = true}
directories = {workspace = true}

[dev-dependencies]
tempfile = {workspace = true}
assert_cmd = {workspace = true}
base64 = {workspace = true}
ibc-types = {workspace = true, default-features = true}
ibc-proto = {workspace = true, default-features = false, features = ["server"]}
penumbra-proof-params = {workspace = true, features = [
    "bundled-proving-keys",
    "download-proving-keys",
], default-features = true}
