[package]
name = "penumbra-crypto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decaf377 = { git = "https://github.com/penumbra-zone/decaf377" }
poseidon377 = { git = "https://github.com/penumbra-zone/poseidon377" }
hex = "0.4"
blake2b_simd = "0.5"
ark-ff = "0.3"
once_cell = "1.8"
# only needed because ark-ff doesn't display correctly
num-bigint = "0.4"
