[package]
name = "penumbra-parameter-setup"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[dependencies]
ark-groth16 = { workspace = true }
ark-serialize = { workspace = true }
decaf377 = { workspace = true, features = ["r1cs"] }
penumbra-community-pool = { workspace = true , features = ["component"] }
penumbra-dex = { workspace = true }
penumbra-governance = { workspace = true }
penumbra-proof-params = { workspace = true }
penumbra-proof-setup = { workspace = true, features = ["parallel"] }
penumbra-shielded-pool = { workspace = true, features = ["parallel"] }
penumbra-stake = { workspace = true, features = ["component"] }
rand_core = { workspace = true }
