[package]
name = "penumbra-parameter-setup"
version = {workspace = true}
edition = {workspace = true}
publish = false

[dependencies]
penumbra-proof-params = {workspace = true, default-features = true}
penumbra-proof-setup = {workspace = true, features = [
    "parallel",
]}
penumbra-dex = {workspace = true, default-features = true}
penumbra-community-pool = {workspace = true, features = [
    "component",
], default-features = true}
penumbra-governance = {workspace = true, default-features = true}
penumbra-shielded-pool = {workspace = true, features = [
    "parallel",
], default-features = true}
penumbra-stake = {workspace = true, features = [
    "component",
], default-features = true}
ark-groth16 = {workspace = true}
ark-serialize = {workspace = true}
decaf377 = {workspace = true, features = ["r1cs"], default-features = true}
rand_core = {workspace = true}
