[package]
name = "penumbra-parameter-setup"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
penumbra-proof-params = { path = "../../crates/crypto/proof-params" }
penumbra-proof-setup = { path = "../../crates/crypto/proof-setup", features = [
    "parallel",
] }
penumbra-dex = { path = "../../crates/core/component/dex/" }
penumbra-community-pool = { path = "../../crates/core/component/community-pool/", features = [
    "component",
] }
penumbra-governance = { path = "../../crates/core/component/governance/" }
penumbra-shielded-pool = { path = "../../crates/core/component/shielded-pool/", features = [
    "parallel",
] }
penumbra-stake = { path = "../../crates/core/component/stake/", features = [
    "component",
] }
ark-groth16 = { workspace = true }
ark-serialize = { workspace = true }
decaf377 = { workspace = true, features = ["r1cs"] }
rand_core = { workspace = true }
