[package]
name = "penumbra-parameter-setup"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
penumbra-crypto = { path = "../../crypto/" }
ark-groth16 = "0.3"
ark-serialize = "0.3"
decaf377 = { version = "0.3", features = ["r1cs"] }
