[package]
name = "decaf377-frost"
version = "0.63.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = { version = "0.4", default_features = false }
blake2b_simd = "0.5"
decaf377 = "0.5"
decaf377-rdsa = "0.7"
frost-core = "0.7"
frost-rerandomized = "0.7"
rand_core = { version = "0.6.4", features = ["getrandom"] }
penumbra-proto = { path = "../../proto/" }
