nodes:
  - external_address: 35.202.100.199:26656
    moniker: phobos-seed
    seed_mode: true
  - external_address: 34.16.34.194:26656
    moniker: deimos
  - external_address: 34.173.166.32:26656
    moniker: naid
