[package]
name = "penumbra-stake"
version = "0.55.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = [
    "penumbra-component",
    "penumbra-storage",
    "penumbra-proto/penumbra-storage",
    "penumbra-chain/component",
    "penumbra-sct/component",
    "tokio",
    "im",
    "futures",
]
proving-keys = ["penumbra-proof-params/proving-keys"]
default = ["component", "proving-keys"]
docsrs = []

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../../../proto" }
penumbra-storage = { path = "../../../storage", default-features = false, optional = true }
penumbra-tct = { path = "../../../crypto/tct" }
penumbra-proof-params = { path = "../../../crypto/proof-params" }
penumbra-crypto = { path = "../../crypto" }
penumbra-component = { path = "../component", default-features = false, optional = true }
penumbra-shielded-pool = { path = "../shielded-pool", default-features = false }
penumbra-sct = { path = "../sct", default-features = false }
penumbra-dao = { path = "../dao", default-features = false }
penumbra-chain = { path = "../chain", default-features = false }

# Penumbra dependencies
decaf377 = {version = "0.4", features = ["r1cs"] }
decaf377-rdsa = { version = "0.6" }
ark-r1cs-std = {version = "0.4", default-features = false }
ark-relations = "0.4"
ark-ff = { version = "0.4", default_features = false }
ark-serialize = "0.4"
ark-groth16 = {version = "0.4", default-features = false}
ark-snark = "0.4"
tokio = { version = "1.21.1", features = ["full", "tracing"], optional = true }
im = { version = "15.1.0", optional = true }
futures = { version = "0.3", optional = true }
async-trait = { version = "0.1.52" }
tendermint = { version = "0.32.0" }
anyhow = "1"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_with = "2.2"
metrics = "0.19.0"
sha2 = "0.9"
serde_unit_struct = "0.1"
bech32 = "0.8"
regex = "1.5"
once_cell = "1.8"
bitvec = "1"
hex = "0.4"
base64 = "0.20"
rand_core = "0.6"
rand_chacha = "0.3"

[dev-dependencies]
ed25519-consensus = "2"
rand_chacha = "0.3"
penumbra-transaction = { path = "../../transaction", features = ["parallel"] }
tracing-subscriber = "0.3"
proptest = "1" 

[build-dependencies]
vergen = "5"
