name: Post to Bluesky
on:
  pull_request:
    types:
      - closed

jobs:
  post_on_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: myConsciousness/bluesky-post@v3
        with:
          text: "Merged PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}\n\n${{ github.event.pull_request.html_url }}"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
  
