name: Update protobuf docs
# We want to rebuild on every commit to main, and also for named testnet tags,
# so that API users can pick a tagged version of the protobuf definitions
# to use against a matching testnet.
on:
  push:
    branches:
      - main
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
        with:
          buf_api_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input: 'proto'
      - uses: bufbuild/buf-lint-action@v1
       with:
         input: 'proto'
      # Disabled because we don't have any changes to compare against
      # - uses: bufbuild/buf-breaking-action@v1
      #   with:
      #     # The 'main' branch of the GitHub repository that defines the module.
      #     against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main'
      #     input: 'proto'
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: 'proto/proto'
