name: buf-pull-request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
        with:
          input: 'proto'
      # Disabled because we have a lot of lint errors we can't fix while there
      # are in-flight proto changes
      # - uses: bufbuild/buf-lint-action@v1
      #  with:
      #    input: 'proto'
      # Disabled because we don't have any changes to compare against
      # - uses: bufbuild/buf-breaking-action@v1
      #   with:
      #     # The 'main' branch of the GitHub repository that defines the module.
      #     against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main'
      #     input: 'proto'
