---
# Deploys the latest changes on 'main' branch, via a container
# image tagged with 'main', to testnet-preview.penumbra.zone.
name: Deploy Testnet Preview (Kubernetes)
on:
  workflow_dispatch:
    inputs:
      nvals:
        description: 'Number of validators at genesis'
        required: true
        default: '2'
      nfullnodes:
        description: 'Number of fullnodes at genesis'
        required: true
        default: '2'
      image_repository:
        description: 'Docker image to deploy'
        required: true
        default: 'ghcr.io/penumbra-zone/penumbra'
      image_tag:
        description: 'Docker image tag to deploy'
        # The container tag "main" comes from the name of the main branch.
        # It's important we deploy this tag for preview, rather than "latest",
        # as "latest" maps to the most recent tag (i.e. weekly testnet).
        default: "main"
        required: true
      image_uid_gid:
        description: 'Docker image user uid:gid'
        required: true
        default: '1000:1000'
  push:
    branches:
      - main

jobs:
  build-container:
    uses: ./.github/workflows/containers.yml
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Deploy to Testnet Preview
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: testnet-preview
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - id: gcloudauth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/1006847873719/locations/global/workloadIdentityPools/gh-runner-pool/providers/my-provider'
          service_account: 'github-actions@penumbra-sl-testnet.iam.gserviceaccount.com'

      - name: get gke credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: testnet
          project_id: penumbra-sl-testnet
          location: us-central1

      - name: deploy
        run: |-
          cd deployments/
          export NVALS='${{ github.event.inputs.nvals }}'
          export NFULLNODES='${{ github.event.inputs.nfullnodes }}'
          export IMAGE='${{ github.event.inputs.image_repository }}'
          export PENUMBRA_VERSION='${{ github.event.inputs.image_tag }}'
          export PENUMBRA_UID_GID='${{ github.event.inputs.image_uid_gid }}'
          export HELM_RELEASE='penumbra-testnet-preview'
          ./ci.sh
