name: Render and Deploy Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    name: Render and deploy protocol and API docs
    timeout-minutes: 30
    runs-on: buildjet-16vcpu-ubuntu-2004
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Load Rust caching
        uses: Swatinem/rust-cache@v1
      - name: Load get-version action to grab version component of deployment path
        uses: battila7/get-version-action@v2
        id: get_version
      - name: Print version component of deployment path
        run: |
          echo ${{ steps.get_version.outputs.version }}
      - name: Install mdbook
        run: |
          cargo install mdbook mdbook-katex mdbook-mermaid

      # This is disabled for now because it broke during the proto reorganization.
      # We are currently rendering docs by pushing protos to Buf.build.
      #
      #- name: Install protobuf compiler
      #  run: |
      #    curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.2/protoc-21.2-linux-x86_64.zip
      #    unzip protoc-21.2-linux-x86_64.zip -d $HOME/.local
      #
      #- name: Install Golang toolchain
      #  uses: actions/setup-go@v3
      #  with:
      #    go-version: '^1.18.3'
      #- name: Install protoc-gen-doc
      #  run: |
      #    go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
      #
      #- name: Build proto docs
      #  run: |
      #    export PATH="$PATH:~/go/bin:$HOME/.local/bin"
      #    protoc --doc_out=./docs/protobuf --doc_opt=html,index.html -I ./proto/proto:proto/ibc-go-vendor proto/proto/**/*.proto proto/proto/*.proto
      #    cd docs/protobuf
      #    if [ -d "firebase-tmp" ]; then rm -rf firebase-tmp; fi
      #    mkdir -p firebase-tmp/${{ steps.get_version.outputs.version }}
      #    cp index.html firebase-tmp/${{ steps.get_version.outputs.version }}
      #- name: Deploy proto docs to firebase
      #  uses: w9jds/firebase-action@v2.0.0
      #  with:
      #    args: deploy
      #  env:
      #    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #    PROJECT_ID: penumbra-protobuf
      #    PROJECT_PATH: docs/protobuf

      - name: Build API docs
        run: ./deployments/scripts/rust-docs

      - name: Move API docs to subdirectory
        run: |
          cd docs/rustdoc
          if [ -d "firebase-tmp" ]; then rm -rf firebase-tmp; fi
          mkdir firebase-tmp
          mv ../../target/doc firebase-tmp/${{ steps.get_version.outputs.version }}
          # Copy in the static index file
          cp index.html firebase-tmp/${{ steps.get_version.outputs.version }}

      - name: Deploy API docs to firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: penumbra-doc
          PROJECT_PATH: docs/rustdoc

      - name: Build protocol spec
        run: |
          cd docs/protocol && mdbook build
      - name: Move protocol spec to subdirectory
        run: |
          cd docs/protocol
          if [ -d "firebase-tmp" ]; then rm -rf firebase-tmp; fi
          mkdir firebase-tmp
          mv book/html firebase-tmp/${{ steps.get_version.outputs.version }}
          tree firebase-tmp
      - name: Deploy protocol spec to firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: penumbra-protocol
          PROJECT_PATH: docs/protocol

      - name: Build software guide
        run: |
          cd docs/guide && mdbook build
      - name: Move software guide to subdirectory
        run: |
          cd docs/guide
          if [ -d "firebase-tmp" ]; then rm -rf firebase-tmp; fi
          mkdir firebase-tmp
          mv book/html firebase-tmp/${{ steps.get_version.outputs.version }}
          tree firebase-tmp
      - name: Deploy software guide to firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: penumbra-guide
          PROJECT_PATH: docs/guide
