name: wasm-npm-publish

on:
  push:
    tags:
      - '*-?v[0-9]+*'
  workflow_call:
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  publish-wasm-to-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/wasm/publish
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Download prebuilt binary for wasm-pack; faster than `cargo install`.
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Install npm deps
        run: npm install

      - name: Set publish config
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      # Will run wasm-pack and publish javascript packages to npm
      - name: Compile wasm & publish to npm
        run: npm run publish-wasm
