name: Smoke Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke_test:
    runs-on: buildjet-16vcpu-ubuntu-2004
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    environment: smoke-test
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Load rust cache
        uses: astriaorg/buildjet-rust-cache@v2.5.1

      - name: Install cometbft binary
        run: |
          curl -L -O "https://github.com/cometbft/cometbft/releases/download/v0.34.27/cometbft_0.34.27_linux_amd64.tar.gz"
          tar -xzf "cometbft_0.34.27_linux_amd64.tar.gz" cometbft
          mkdir -p $HOME/bin
          cp cometbft $HOME/bin
          echo $PATH
          export PATH=$HOME/bin:$PATH
          which cometbft

      - name: Run the smoke test suite
        run: |
          export PATH=$HOME/bin:$PATH
          ./deployments/scripts/smoke-test.sh
        env:
          TESTNET_RUNTIME: 2m
