name: Smoke Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke_test:
    runs-on: buildjet-16vcpu-ubuntu-2004
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    environment: smoke-test
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Log in to the Docker Hub container registry (for pulls)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the testnet.
        run: |
          ./scripts/docker_compose_freshstart.sh
          chmod -R 777 ~/.penumbra/testnet_data
          docker-compose build

      - name: Run testnet for smoke test duration.
        run: timeout --preserve-status $TESTNET_RUNTIME docker-compose up --exit-code-from pd-node0
        env:
          TESTNET_RUNTIME: 5m

      - name: Now start testnet in the background so we can run integration tests.
        run: |
          docker-compose up --detach

      # DOC: please update the devnet guide if you change this (see "How to run smoke-tests")
      - name: Run integration tests against localhost.
        run: cargo test --features nct-divergence-check --package pcli -- --ignored --test-threads 1 --nocapture
        env:
          PENUMBRA_NODE_HOSTNAME: 127.0.0.1
          PCLI_UNLEASH_DANGER: yes
          RUST_LOG: pcli=debug,penumbra=debug
