name: Smoke Test
on:
  push:
    branches:
      - main

jobs:
  smoke_test:
    runs-on: buildjet-16vcpu-ubuntu-2004
    environment: smoke-test
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build the testnet.
        run: |
          ./scripts/docker_compose_freshstart.sh
          chmod -R 777 ~/.penumbra/testnet_data
          docker-compose build

      - name: Run testnet for smoke test duration.
        run: timeout --preserve-status $TESTNET_RUNTIME docker-compose up --exit-code-from pd-node0
        env:
          TESTNET_RUNTIME: 5m

      - name: Now start testnet again in the background so we can run integration tests.
        run: docker-compose up --detach pd-node0

      - name: Run integration tests against localhost.
        run: cargo test --package pcli -- --ignored
        env:
          PENUMBRA_NODE_HOSTNAME: 127.0.0.1
          PCLI_UNLEASH_DANGER: yes
