name: Smoke Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke_test:
    runs-on: buildjet-16vcpu-ubuntu-2204
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    environment: smoke-test
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Load rust cache
        uses: astriaorg/buildjet-rust-cache@v2.5.1

      - name: Install cometbft binary
        run: ./deployments/scripts/install-cometbft

      - name: Run the smoke test suite
        run: |
          export PATH="$HOME/bin:$PATH"
          ./deployments/scripts/smoke-test.sh

      - name: Display comet logs
        if: always()
        run: cat deployments/logs/comet.log
      - name: Display pd runtime logs
        if: always()
        run: cat deployments/logs/pd.log
      - name: Display pd test logs
        if: always()
        run: cat deployments/logs/pd-tests.log
      - name: Display pclientd logs
        if: always()
        run: cat deployments/logs/pclientd.log
      - name: Display pcli logs
        if: always()
        run: cat deployments/logs/pcli.log
    env:
      TESTNET_RUNTIME: 2m

