# Since the summoner smoke test takes ~18m to run, we don't want
# to run it on every PR. Instead, we want to run it on demand,
# and for now on merges into `main`.
name: Summoner smoke Test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  smoke_test:
    runs-on: buildjet-16vcpu-ubuntu-2204
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    environment: smoke-test
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Load rust cache
        uses: astriaorg/buildjet-rust-cache@v2.5.1

      - name: Install cometbft binary
        run: ./deployments/scripts/install-cometbft

      - name: Run e2e test of summoner
        run: |
          export PATH="$HOME/bin:$PATH"
          ./deployments/scripts/smoke-summoner.sh
