---
# A process-compose configuration for running a local Penumbra devnet.
# This isn't used in scripts anywhere (yet?) but serves as a reference point.
# Potentially could be integrated with e.g. https://www.jetify.com/devbox later on.
#
version: "0.5"

# Env vars set here will be accessible to all processes.
environment:
  - "RUST_LOG=info,network_integration=debug,pclientd=debug,pcli=info,pd=info,penumbra=info"

log_level: info
is_strict: true
# Interleave logs from all services in single file, so it's greppable.
log_location: deployments/logs/dev-env-combined.log

processes:
  # Run pd validator based on generated network.
  pd:
    command: cargo run --release --bin pd -- start
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/"
        port: 8080
      failure_threshold: 2
      initial_delay_seconds: 5
      period_seconds: 5

  # Run CometBFT for consensus driver.
  cometbft:
    command: cometbft --log_level=debug --home ~/.penumbra/network_data/node0/cometbft start
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/"
        port: 26657
      failure_threshold: 2
      initial_delay_seconds: 5
      period_seconds: 5
    depends_on:
      pd:
        condition: process_healthy
