[package]
name = "penumbra-component"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16", features = ["full", "tracing"]}
penumbra-transaction = { path = "../transaction" }
penumbra-chain = { path = "../chain" }
async-trait = "0.1.52"
tonic = "0.6.1"
tendermint = "0.24.0-pre.1"
anyhow = "1"
